import { ModuleType } from '@prisma/client';

// Public business identities are sourced from web listings in djibouti_seed_sources.md.
// Some app-only fields such as catalog pricing, menus, consultation fees, and availability
// are curated seed estimates when public listings did not expose structured values.

export const djiboutiShoppingStores = [
  {
    id: 'store-djib-smart',
    name: 'Djib Smart',
    slug: 'djib-smart',
    tagline: 'Phones, gadgets, and everyday electronics around central La Plaine.',
    description:
      'Local electronics retailer listed in Djibouti with smartphone accessories, small gadgets, and tech essentials.',
    imageUrl: null,
    rating: 4.4,
    reviewCount: 18,
    badge: 'Local Favorite',
    minPrice: 12,
    maxPrice: 699,
    highlightsJson: ['Mobile accessories', 'Djibouti City pickup', 'Curated electronics'],
  },
  {
    id: 'store-djibshopp',
    name: 'Djibshopp',
    slug: 'djibshopp',
    tagline: 'Connected devices and digital gear around Rue de Rome and central Djibouti.',
    description:
      'Djibshopp appears across local business listings as a Djibouti retailer for consumer electronics and accessories.',
    imageUrl: null,
    rating: 4.3,
    reviewCount: 12,
    badge: 'Trending',
    minPrice: 9,
    maxPrice: 499,
    highlightsJson: ['Smart devices', 'Giftable tech', 'Quick accessory restocks'],
  },
  {
    id: 'store-nougaprix',
    name: 'Supermarche Nougaprix',
    slug: 'supermarche-nougaprix',
    tagline: 'Imported household goods and daily shopping essentials.',
    description:
      'Nougaprix is a known Djibouti supermarket brand and is used here as a local general merchandise storefront.',
    imageUrl: null,
    rating: 4.2,
    reviewCount: 26,
    badge: 'Established',
    minPrice: 6,
    maxPrice: 189,
    highlightsJson: ['Household picks', 'Imported staples', 'Well-known local chain'],
  },
  {
    id: 'store-cash-center',
    name: 'Cash Center',
    slug: 'cash-center',
    tagline: 'Large-format supermarket with home, kitchen, and family essentials.',
    description:
      'Cash Center is a Djibouti supermarket brand with a broad mix of household and lifestyle products.',
    imageUrl: null,
    rating: 4.3,
    reviewCount: 31,
    badge: 'Popular',
    minPrice: 5,
    maxPrice: 249,
    highlightsJson: ['Household essentials', 'Kitchen section', 'Family shopping'],
  },
  {
    id: 'store-le-bonheur',
    name: 'Le Bonheur Pret A Porter',
    slug: 'le-bonheur-pret-a-porter',
    tagline: 'Fashion basics and ready-to-wear picks in Djibouti.',
    description:
      'Le Bonheur Pret A Porter is a local clothing shop used here to anchor the fashion catalog in Djibouti.',
    imageUrl: null,
    rating: 4.1,
    reviewCount: 9,
    badge: null,
    minPrice: 14,
    maxPrice: 119,
    highlightsJson: ['Ready-to-wear', 'Everyday fashion', 'Local clothing shop'],
  },
  {
    id: 'store-elixir',
    name: "L'Elixir Parfumerie & Cosmetiques",
    slug: 'lelixir-parfumerie-cosmetiques',
    tagline: 'Beauty, fragrance, and premium cosmetic picks in Djibouti.',
    description:
      'L Elixir is a publicly listed Djibouti beauty and cosmetics retailer with fragrance and skincare positioning.',
    imageUrl: null,
    rating: 4.5,
    reviewCount: 31,
    badge: 'Top Rated',
    minPrice: 8,
    maxPrice: 145,
    highlightsJson: ['Beauty retail', 'Fragrance selection', 'Well-rated local shop'],
  },
  {
    id: 'store-top-crazy',
    name: 'Magasin Top Crazy',
    slug: 'magasin-top-crazy',
    tagline: 'Menswear and everyday fashion on Street Rome.',
    description:
      'Magasin Top Crazy is listed in Djibouti City as a clothing and menswear store near Liban Electronic.',
    imageUrl: null,
    rating: 4.5,
    reviewCount: 11,
    badge: 'Trending',
    minPrice: 12,
    maxPrice: 139,
    highlightsJson: ['Menswear', 'Street Rome location', 'Local fashion'],
  },
  {
    id: 'store-bawadi-mall',
    name: 'Bawadi Mall Djibouti',
    slug: 'bawadi-mall-djibouti',
    tagline: 'Mall-based shopping for electronics, pharmacy, and daily needs.',
    description:
      'Bawadi Mall Djibouti appears in local listings and is used here as a mixed-retail shopping destination.',
    imageUrl: null,
    rating: 4.5,
    reviewCount: 14,
    badge: 'Mall',
    minPrice: 5,
    maxPrice: 320,
    highlightsJson: ['Mixed retail', 'Convenient shopping', 'Popular mall'],
  },
  {
    id: 'store-abdi',
    name: 'Abdi',
    slug: 'abdi-djibouti',
    tagline: 'Hardware, accessories, and utility shopping in Djibouti.',
    description:
      'Abdi is listed in Djibouti for hardware and clothing accessories and is mapped to practical shopping inventory.',
    imageUrl: null,
    rating: 4.0,
    reviewCount: 6,
    badge: null,
    minPrice: 7,
    maxPrice: 180,
    highlightsJson: ['Hardware basics', 'Accessories', 'Utility retail'],
  },
  {
    id: 'store-team-max',
    name: 'Team Max Fashion Djibouti',
    slug: 'team-max-fashion-djibouti',
    tagline: 'Streetwear and ready-to-wear fashion in Djibouti City.',
    description:
      'Team Max Fashion Djibouti is listed as a clothing store and is used here to widen local fashion coverage.',
    imageUrl: null,
    rating: 4.5,
    reviewCount: 10,
    badge: 'Popular',
    minPrice: 11,
    maxPrice: 129,
    highlightsJson: ['Streetwear', 'Local fashion', 'Rue de Venice'],
  },
  {
    id: 'store-sympa-shop',
    name: 'Sympa Shop',
    slug: 'sympa-shop',
    tagline: 'Fashion-forward clothing and everyday city style.',
    description:
      'Sympa Shop appears on Djibouti clothing listings and is used for a wider apparel storefront mix.',
    imageUrl: null,
    rating: 5,
    reviewCount: 6,
    badge: 'Top Rated',
    minPrice: 10,
    maxPrice: 119,
    highlightsJson: ['Clothing store', 'Rue de Rome', 'Well-rated'],
  },
  {
    id: 'store-arta-electronique',
    name: 'Arta electronique',
    slug: 'arta-electronique',
    tagline: 'Electronics and household tech in Djibouti.',
    description:
      'Arta electronique is listed among Djibouti electronic stores and is mapped to the local electronics catalog.',
    imageUrl: null,
    rating: 4,
    reviewCount: 7,
    badge: null,
    minPrice: 14,
    maxPrice: 580,
    highlightsJson: ['Electronics', 'Household appliances', 'Local retailer'],
  },
  {
    id: 'store-sos-high-tech',
    name: 'Sos High Tech',
    slug: 'sos-high-tech',
    tagline: 'Devices, repairs, and high-tech shopping support.',
    description:
      'Sos High Tech is a Djibouti electronics listing used to strengthen the technology-shopping category.',
    imageUrl: null,
    rating: 3.5,
    reviewCount: 7,
    badge: null,
    minPrice: 8,
    maxPrice: 650,
    highlightsJson: ['Electronics', 'Rue Pierre Curie', 'Tech support vibe'],
  },
  {
    id: 'store-magasin-numerique-2',
    name: 'Magasin numerique 2',
    slug: 'magasin-numerique-2',
    tagline: 'Phone accessories and digital essentials on Rue de Rome.',
    description:
      'Magasin numerique 2 is a highly rated electronics listing in Djibouti City.',
    imageUrl: null,
    rating: 4.5,
    reviewCount: 8,
    badge: 'Trending',
    minPrice: 7,
    maxPrice: 420,
    highlightsJson: ['Digital accessories', 'Rue de Rome', 'Local electronics'],
  },
  {
    id: 'store-abdoulbasset',
    name: 'Ets Abdoulbasset',
    slug: 'ets-abdoulbasset',
    tagline: 'Avenue 13 department-store shopping in La Plaine.',
    description:
      'Ets Abdoulbasset is a well-known Avenue 13 retail address in La Plaine and is mapped here as a broad shopping storefront.',
    imageUrl: null,
    rating: 4.2,
    reviewCount: 10,
    badge: 'Avenue 13',
    minPrice: 6,
    maxPrice: 210,
    highlightsJson: ['Avenue 13', 'La Plaine', 'Department-store assortment'],
  },
  {
    id: 'store-wassel-av13',
    name: 'Wassel Quincaillerie - AV.13',
    slug: 'wassel-quincaillerie-av13',
    tagline: 'Household equipment and utility shopping on Avenue 13.',
    description:
      'Wassel Quincaillerie is a known Avenue 13 retail point in Djibouti City for household and utility shopping.',
    imageUrl: null,
    rating: 4.1,
    reviewCount: 12,
    badge: 'Utility',
    minPrice: 8,
    maxPrice: 230,
    highlightsJson: ['Avenue 13', 'La Plaine', 'Household equipment'],
  },
  {
    id: 'store-centre-commercial-liban',
    name: 'Centre Commercial Liban',
    slug: 'centre-commercial-liban',
    tagline: 'Neighborhood shopping and hardware on Avenue 13 Cheik Houmed.',
    description:
      'Centre Commercial Liban is used here as a practical local retail stop serving Avenue 13 and surrounding La Plaine blocks.',
    imageUrl: null,
    rating: 4.0,
    reviewCount: 6,
    badge: null,
    minPrice: 7,
    maxPrice: 199,
    highlightsJson: ['Avenue 13 Cheik Houmed', 'La Plaine', 'Neighborhood retail'],
  },
] as const;

export const djiboutiShoppingProducts = [
  {
    id: 'p1',
    moduleType: ModuleType.SHOPPING,
    categoryId: 'shopping-electronics',
    shopId: 'store-djib-smart',
    name: 'Samsung Galaxy A55 5G',
    brand: 'Samsung',
    description:
      'Representative smartphone catalog item for Djib Smart, curated for the Djibouti electronics storefront.',
    price: 379.99,
    originalPrice: 419.99,
    rating: 4.5,
    reviewCount: 18,
    imageUrlsJson: [],
    colorsJson: ['Navy', 'Lemon', 'Ice Blue'],
    sizesJson: ['128GB'],
    tagsJson: ['Popular'],
    featuresJson: ['5G ready', 'AMOLED display', 'Fast charging'],
    badge: 'Popular',
    inStock: true,
    isOrganic: false,
    metadata: {
      sourceBusiness: 'Djib Smart',
      sourcingNote: 'Representative product added because public local inventory is not published online.',
    },
  },
  {
    id: 'p2',
    moduleType: ModuleType.SHOPPING,
    categoryId: 'shopping-accessories',
    shopId: 'store-djibshopp',
    name: 'Anker 20000mAh Power Bank',
    brand: 'Anker',
    description:
      'Portable charging accessory seeded for Djibshopp based on its consumer electronics profile.',
    price: 44.99,
    originalPrice: null,
    rating: 4.4,
    reviewCount: 12,
    imageUrlsJson: [],
    colorsJson: ['Black'],
    sizesJson: [],
    tagsJson: ['Travel'],
    featuresJson: ['Fast charge', 'USB-C input', 'High-capacity battery'],
    badge: null,
    inStock: true,
    isOrganic: false,
    metadata: {
      sourceBusiness: 'Djibshopp',
      sourcingNote: 'Representative product added because public local inventory is not published online.',
    },
  },
  {
    id: 'p3',
    moduleType: ModuleType.SHOPPING,
    categoryId: 'shopping-home',
    shopId: 'store-cash-center',
    name: 'Philips Blender 1.5L',
    brand: 'Philips',
    description:
      'Household appliance seeded for Cash Center to reflect a general home-and-kitchen retail assortment.',
    price: 69.99,
    originalPrice: 82,
    rating: 4.2,
    reviewCount: 10,
    imageUrlsJson: [],
    colorsJson: ['White'],
    sizesJson: [],
    tagsJson: ['Kitchen'],
    featuresJson: ['1.5L jar', 'Multi-speed control', 'Dishwasher-safe parts'],
    badge: null,
    inStock: true,
    isOrganic: false,
    metadata: {
      sourceBusiness: 'Cash Center',
      sourcingNote: 'Representative product added because public local inventory is not published online.',
    },
  },
  {
    id: 'p4',
    moduleType: ModuleType.SHOPPING,
    categoryId: 'shopping-home',
    shopId: 'store-nougaprix',
    name: 'Tefal Non-Stick Cookware Set',
    brand: 'Tefal',
    description:
      'Representative cookware listing for Nougaprix, matching the store household-goods positioning.',
    price: 89.99,
    originalPrice: null,
    rating: 4.1,
    reviewCount: 8,
    imageUrlsJson: [],
    colorsJson: ['Black'],
    sizesJson: ['5-piece'],
    tagsJson: ['Home'],
    featuresJson: ['Non-stick coating', 'Gas-stove ready', 'Family cooking set'],
    badge: null,
    inStock: true,
    isOrganic: false,
    metadata: {
      sourceBusiness: 'Supermarche Nougaprix',
      sourcingNote: 'Representative product added because public local inventory is not published online.',
    },
  },
  {
    id: 'p5',
    moduleType: ModuleType.SHOPPING,
    categoryId: 'shopping-clothing',
    shopId: 'store-le-bonheur',
    name: 'Classic Linen Shirt',
    brand: 'Le Bonheur',
    description:
      'Seeded fashion essential aligned with the ready-to-wear profile of Le Bonheur Pret A Porter.',
    price: 29.99,
    originalPrice: 36,
    rating: 4.1,
    reviewCount: 6,
    imageUrlsJson: [],
    colorsJson: ['White', 'Beige', 'Navy'],
    sizesJson: ['S', 'M', 'L', 'XL'],
    tagsJson: ['Breathable'],
    featuresJson: ['Lightweight linen blend', 'Warm-weather fit', 'Everyday wear'],
    badge: null,
    inStock: true,
    isOrganic: false,
    metadata: {
      sourceBusiness: 'Le Bonheur Pret A Porter',
      sourcingNote: 'Representative product added because public local inventory is not published online.',
    },
  },
  {
    id: 'p6',
    moduleType: ModuleType.SHOPPING,
    categoryId: 'shopping-accessories',
    shopId: 'store-djib-smart',
    name: 'JBL Tune 520BT Headphones',
    brand: 'JBL',
    description:
      'Wireless audio accessory seeded for the Djib Smart storefront to strengthen the local tech catalog.',
    price: 59.99,
    originalPrice: null,
    rating: 4.4,
    reviewCount: 11,
    imageUrlsJson: [],
    colorsJson: ['Black', 'Blue'],
    sizesJson: [],
    tagsJson: ['Wireless'],
    featuresJson: ['Bluetooth', 'Foldable design', 'Long battery life'],
    badge: null,
    inStock: true,
    isOrganic: false,
    metadata: {
      sourceBusiness: 'Djib Smart',
      sourcingNote: 'Representative product added because public local inventory is not published online.',
    },
  },
  {
    id: 'p7',
    moduleType: ModuleType.SHOPPING,
    categoryId: 'shopping-accessories',
    shopId: 'store-elixir',
    name: 'Lattafa Yara Eau de Parfum',
    brand: 'Lattafa',
    description:
      'Representative fragrance item seeded for the beauty retail profile of L Elixir Parfumerie & Cosmetiques.',
    price: 34.99,
    originalPrice: null,
    rating: 4.6,
    reviewCount: 15,
    imageUrlsJson: [],
    colorsJson: [],
    sizesJson: ['100ml'],
    tagsJson: ['Fragrance'],
    featuresJson: ['Long-lasting scent', 'Gift-friendly bottle'],
    badge: 'Top Rated',
    inStock: true,
    isOrganic: false,
    metadata: {
      sourceBusiness: "L'Elixir Parfumerie & Cosmetiques",
      sourcingNote: 'Representative product added because public local inventory is not published online.',
    },
  },
  {
    id: 'p8',
    moduleType: ModuleType.SHOPPING,
    categoryId: 'shopping-clothing',
    shopId: 'store-top-crazy',
    name: 'Slim Fit Casual Blazer',
    brand: 'Top Crazy',
    description:
      'Curated menswear piece aligned with Magasin Top Crazy and its local clothing-store profile.',
    price: 54.99,
    originalPrice: 68,
    rating: 4.4,
    reviewCount: 9,
    imageUrlsJson: [],
    colorsJson: ['Black', 'Navy'],
    sizesJson: ['M', 'L', 'XL'],
    tagsJson: ['Menswear'],
    featuresJson: ['Smart casual look', 'Light structure', 'Evening-ready'],
    badge: null,
    inStock: true,
    isOrganic: false,
    metadata: {
      sourceBusiness: 'Magasin Top Crazy',
      sourcingNote: 'Representative product added because public local inventory is not published online.',
    },
  },
  {
    id: 'p9',
    moduleType: ModuleType.SHOPPING,
    categoryId: 'shopping-home',
    shopId: 'store-bawadi-mall',
    name: 'Kenwood Electric Kettle',
    brand: 'Kenwood',
    description:
      'Representative household appliance used for the Bawadi Mall mixed-retail shopping catalog.',
    price: 24.99,
    originalPrice: null,
    rating: 4.3,
    reviewCount: 8,
    imageUrlsJson: [],
    colorsJson: ['Silver'],
    sizesJson: ['1.7L'],
    tagsJson: ['Home essential'],
    featuresJson: ['Fast boil', 'Auto shutoff', 'Cordless base'],
    badge: null,
    inStock: true,
    isOrganic: false,
    metadata: {
      sourceBusiness: 'Bawadi Mall Djibouti',
      sourcingNote: 'Representative product added because public local inventory is not published online.',
    },
  },
  {
    id: 'p10',
    moduleType: ModuleType.SHOPPING,
    categoryId: 'shopping-home',
    shopId: 'store-abdi',
    name: 'Heavy Duty Tool Set',
    brand: 'Abdi',
    description:
      'Utility hardware item seeded for Abdi to reflect its hardware-store identity in Djibouti.',
    price: 42.99,
    originalPrice: 49.99,
    rating: 4.1,
    reviewCount: 5,
    imageUrlsJson: [],
    colorsJson: [],
    sizesJson: ['32-piece'],
    tagsJson: ['Hardware'],
    featuresJson: ['Household basics', 'Storage case', 'Multi-use kit'],
    badge: null,
    inStock: true,
    isOrganic: false,
    metadata: {
      sourceBusiness: 'Abdi',
      sourcingNote: 'Representative product added because public local inventory is not published online.',
    },
  },
  {
    id: 'p11',
    moduleType: ModuleType.SHOPPING,
    categoryId: 'shopping-clothing',
    shopId: 'store-team-max',
    name: 'Streetwear Cargo Set',
    brand: 'Team Max',
    description:
      'Representative streetwear outfit seeded for Team Max Fashion Djibouti.',
    price: 47.99,
    originalPrice: 59.99,
    rating: 4.4,
    reviewCount: 9,
    imageUrlsJson: [],
    colorsJson: ['Black', 'Khaki'],
    sizesJson: ['M', 'L', 'XL'],
    tagsJson: ['Streetwear'],
    featuresJson: ['Relaxed fit', 'Urban style', 'Matching set'],
    badge: null,
    inStock: true,
    isOrganic: false,
    metadata: { sourceBusiness: 'Team Max Fashion Djibouti', sourcingNote: 'Representative product added because public local inventory is not published online.' },
  },
  {
    id: 'p12',
    moduleType: ModuleType.SHOPPING,
    categoryId: 'shopping-clothing',
    shopId: 'store-sympa-shop',
    name: 'Women Casual Dress',
    brand: 'Sympa Shop',
    description:
      'Curated apparel item aligned with the clothing-store profile of Sympa Shop.',
    price: 31.99,
    originalPrice: null,
    rating: 4.5,
    reviewCount: 6,
    imageUrlsJson: [],
    colorsJson: ['Emerald', 'Black', 'Cream'],
    sizesJson: ['S', 'M', 'L'],
    tagsJson: ['Fashion'],
    featuresJson: ['Light fabric', 'Day-to-evening style'],
    badge: 'Top Rated',
    inStock: true,
    isOrganic: false,
    metadata: { sourceBusiness: 'Sympa Shop', sourcingNote: 'Representative product added because public local inventory is not published online.' },
  },
  {
    id: 'p13',
    moduleType: ModuleType.SHOPPING,
    categoryId: 'shopping-electronics',
    shopId: 'store-arta-electronique',
    name: 'LG 43 Inch Smart TV',
    brand: 'LG',
    description:
      'Representative household electronics item seeded for Arta electronique.',
    price: 329.99,
    originalPrice: 359.99,
    rating: 4.1,
    reviewCount: 7,
    imageUrlsJson: [],
    colorsJson: ['Black'],
    sizesJson: ['43-inch'],
    tagsJson: ['Home tech'],
    featuresJson: ['Smart apps', 'HDMI ports', 'LED display'],
    badge: null,
    inStock: true,
    isOrganic: false,
    metadata: { sourceBusiness: 'Arta electronique', sourcingNote: 'Representative product added because public local inventory is not published online.' },
  },
  {
    id: 'p14',
    moduleType: ModuleType.SHOPPING,
    categoryId: 'shopping-electronics',
    shopId: 'store-sos-high-tech',
    name: 'iPhone 13 Silicone Case',
    brand: 'SOS High Tech',
    description:
      'Accessory-focused product used to populate the SOS High Tech storefront.',
    price: 14.99,
    originalPrice: null,
    rating: 4.0,
    reviewCount: 5,
    imageUrlsJson: [],
    colorsJson: ['Black', 'Blue', 'Red'],
    sizesJson: ['iPhone 13'],
    tagsJson: ['Accessory'],
    featuresJson: ['Shock protection', 'Soft-touch finish'],
    badge: null,
    inStock: true,
    isOrganic: false,
    metadata: { sourceBusiness: 'Sos High Tech', sourcingNote: 'Representative product added because public local inventory is not published online.' },
  },
  {
    id: 'p15',
    moduleType: ModuleType.SHOPPING,
    categoryId: 'shopping-accessories',
    shopId: 'store-magasin-numerique-2',
    name: 'Wireless Earbuds Pro',
    brand: 'MN2',
    description:
      'Seeded audio accessory for Magasin numerique 2 and its digital-gear store profile.',
    price: 27.99,
    originalPrice: 34.99,
    rating: 4.5,
    reviewCount: 8,
    imageUrlsJson: [],
    colorsJson: ['White', 'Black'],
    sizesJson: [],
    tagsJson: ['Wireless'],
    featuresJson: ['Bluetooth', 'Portable charging case'],
    badge: 'Trending',
    inStock: true,
    isOrganic: false,
    metadata: { sourceBusiness: 'Magasin numerique 2', sourcingNote: 'Representative product added because public local inventory is not published online.' },
  },
  {
    id: 'p16',
    moduleType: ModuleType.SHOPPING,
    categoryId: 'shopping-home',
    shopId: 'store-abdoulbasset',
    name: 'Household Storage Organizer Set',
    brand: 'Abdoulbasset',
    description:
      'Practical home item seeded for the Avenue 13 department-store profile of Ets Abdoulbasset.',
    price: 21.99,
    originalPrice: null,
    rating: 4.2,
    reviewCount: 6,
    imageUrlsJson: [],
    colorsJson: ['Gray'],
    sizesJson: ['4-piece'],
    tagsJson: ['Home'],
    featuresJson: ['Stackable', 'Utility storage'],
    badge: null,
    inStock: true,
    isOrganic: false,
    metadata: { sourceBusiness: 'Ets Abdoulbasset', sourcingNote: 'Representative product added because public local inventory is not published online.' },
  },
  {
    id: 'p17',
    moduleType: ModuleType.SHOPPING,
    categoryId: 'shopping-home',
    shopId: 'store-wassel-av13',
    name: 'LED Emergency Lamp',
    brand: 'Wassel',
    description:
      'Utility household item seeded for Wassel Quincaillerie and the Avenue 13 practical-shopping corridor.',
    price: 18.5,
    originalPrice: 22,
    rating: 4.1,
    reviewCount: 7,
    imageUrlsJson: [],
    colorsJson: ['White'],
    sizesJson: [],
    tagsJson: ['Utility'],
    featuresJson: ['Rechargeable', 'Portable light'],
    badge: 'Avenue 13',
    inStock: true,
    isOrganic: false,
    metadata: { sourceBusiness: 'Wassel Quincaillerie - AV.13', sourcingNote: 'Representative product added because public local inventory is not published online.' },
  },
  {
    id: 'p18',
    moduleType: ModuleType.SHOPPING,
    categoryId: 'shopping-home',
    shopId: 'store-centre-commercial-liban',
    name: 'Compact Home Fan',
    brand: 'Liban',
    description:
      'Representative neighborhood retail appliance for Centre Commercial Liban on Avenue 13.',
    price: 26.99,
    originalPrice: null,
    rating: 4.0,
    reviewCount: 5,
    imageUrlsJson: [],
    colorsJson: ['White', 'Black'],
    sizesJson: ['12-inch'],
    tagsJson: ['Cooling'],
    featuresJson: ['Compact size', 'Desk or room use'],
    badge: null,
    inStock: true,
    isOrganic: false,
    metadata: { sourceBusiness: 'Centre Commercial Liban', sourcingNote: 'Representative product added because public local inventory is not published online.' },
  },
] as const;

export const djiboutiPharmacyProducts = [
  {
    id: 'm1',
    moduleType: ModuleType.PHARMACY,
    categoryId: 'pharmacy-pain-relief',
    name: 'Paracetamol 500mg',
    brand: 'Pharmacie Dawo',
    description:
      'Common pain-relief product seeded for Djibouti pharmacy browsing. Pharmacy identity comes from local business listings.',
    price: 4.99,
    originalPrice: null,
    rating: 4.4,
    reviewCount: 10,
    dosage: 'Take 1-2 tablets every 4-6 hours',
    packageSize: '20 Tablets',
    requiresPrescription: false,
    imageUrlsJson: [],
    colorsJson: [],
    sizesJson: [],
    tagsJson: ['Local Pharmacy'],
    featuresJson: ['Everyday fever relief'],
    badge: null,
    inStock: true,
    isOrganic: false,
    metadata: {
      sourceBusiness: 'Pharmacie Dawo',
      sourcingNote: 'Medicine assortment is curated because live pharmacy inventory is not published online.',
    },
  },
  {
    id: 'm2',
    moduleType: ModuleType.PHARMACY,
    categoryId: 'pharmacy-antibiotics',
    name: 'Amoxicillin 500mg',
    brand: 'GPCA',
    description:
      'Prescription antibiotic placeholder for the Djibouti pharmacy catalog, attached to the GPCA pharmacy identity.',
    price: 12.99,
    originalPrice: null,
    rating: 4.5,
    reviewCount: 8,
    dosage: 'Take 1 capsule every 8 hours as prescribed',
    packageSize: '16 Capsules',
    requiresPrescription: true,
    imageUrlsJson: [],
    colorsJson: [],
    sizesJson: [],
    tagsJson: ['Prescription'],
    featuresJson: ['Requires pharmacist review'],
    badge: null,
    inStock: true,
    isOrganic: false,
    metadata: {
      sourceBusiness: 'GPCA',
      sourcingNote: 'Medicine assortment is curated because live pharmacy inventory is not published online.',
    },
  },
  {
    id: 'm3',
    moduleType: ModuleType.PHARMACY,
    categoryId: 'pharmacy-vitamins',
    name: 'Vitamin C 1000mg',
    brand: 'Pharmacie Riyadh',
    description:
      'Immune-support vitamin entry associated with a Djibouti pharmacy listing for search and ordering flows.',
    price: 9.49,
    originalPrice: null,
    rating: 4.3,
    reviewCount: 7,
    dosage: '1 tablet daily',
    packageSize: '30 Tablets',
    requiresPrescription: false,
    imageUrlsJson: [],
    colorsJson: [],
    sizesJson: [],
    tagsJson: ['Wellness'],
    featuresJson: ['Daily supplement'],
    badge: null,
    inStock: true,
    isOrganic: false,
    metadata: {
      sourceBusiness: 'Pharmacie Riyadh',
      sourcingNote: 'Medicine assortment is curated because live pharmacy inventory is not published online.',
    },
  },
  {
    id: 'm4',
    moduleType: ModuleType.PHARMACY,
    categoryId: 'pharmacy-cold-flu',
    name: 'Cold and Flu Relief Syrup',
    brand: 'Pharmacie Dawo',
    description:
      'Seeded symptomatic treatment product for the Djibouti pharmacy module.',
    price: 8.25,
    originalPrice: null,
    rating: 4.2,
    reviewCount: 5,
    dosage: '10ml up to 3 times daily',
    packageSize: '120ml',
    requiresPrescription: false,
    imageUrlsJson: [],
    colorsJson: [],
    sizesJson: [],
    tagsJson: ['Seasonal'],
    featuresJson: ['Soothes cough and congestion'],
    badge: null,
    inStock: true,
    isOrganic: false,
    metadata: {
      sourceBusiness: 'Pharmacie Dawo',
      sourcingNote: 'Medicine assortment is curated because live pharmacy inventory is not published online.',
    },
  },
  {
    id: 'm5',
    moduleType: ModuleType.PHARMACY,
    categoryId: 'pharmacy-vitamins',
    name: 'Bioderma Atoderm Intensive Baume',
    brand: 'GPCA',
    description:
      'Publicly listed dermocosmetic brand available through GPCA channels and seeded into the health catalog.',
    price: 18.99,
    originalPrice: null,
    rating: 4.6,
    reviewCount: 9,
    dosage: 'Apply once or twice daily',
    packageSize: '200ml',
    requiresPrescription: false,
    imageUrlsJson: [],
    colorsJson: [],
    sizesJson: [],
    tagsJson: ['Skincare'],
    featuresJson: ['Dry skin support', 'Family care'],
    badge: 'Dermocosmetic',
    inStock: true,
    isOrganic: false,
    metadata: {
      sourceBusiness: 'GPCA',
      sourcingNote: 'Product family aligns with GPCA public pharmacy content.',
    },
  },
  {
    id: 'm6',
    moduleType: ModuleType.PHARMACY,
    categoryId: 'pharmacy-cold-flu',
    name: 'Sterimar Nasal Spray',
    brand: 'Pharmacie Riyadh',
    description:
      'Curated seasonal care product attached to a real Djibouti pharmacy listing for catalog depth.',
    price: 7.5,
    originalPrice: null,
    rating: 4.2,
    reviewCount: 4,
    dosage: '1 to 2 sprays per nostril as needed',
    packageSize: '100ml',
    requiresPrescription: false,
    imageUrlsJson: [],
    colorsJson: [],
    sizesJson: [],
    tagsJson: ['Cold care'],
    featuresJson: ['Saline cleansing', 'Daily use'],
    badge: null,
    inStock: true,
    isOrganic: false,
    metadata: {
      sourceBusiness: 'Pharmacie Riyadh',
      sourcingNote: 'Medicine assortment is curated because live pharmacy inventory is not published online.',
    },
  },
  {
    id: 'm7',
    moduleType: ModuleType.PHARMACY,
    categoryId: 'pharmacy-pain-relief',
    name: 'Ibuprofen 400mg',
    brand: 'Pharmacie du Mall',
    description:
      'Additional pain-relief item seeded from a real Djibouti pharmacy identity to broaden the health catalog.',
    price: 6.75,
    originalPrice: null,
    rating: 4.3,
    reviewCount: 6,
    dosage: '1 tablet every 8 hours after food',
    packageSize: '20 Tablets',
    requiresPrescription: false,
    imageUrlsJson: [],
    colorsJson: [],
    sizesJson: [],
    tagsJson: ['Popular'],
    featuresJson: ['Pain and inflammation support'],
    badge: null,
    inStock: true,
    isOrganic: false,
    metadata: {
      sourceBusiness: 'Pharmacie du Mall',
      sourcingNote: 'Medicine assortment is curated because live pharmacy inventory is not published online.',
    },
  },
  {
    id: 'm8',
    moduleType: ModuleType.PHARMACY,
    categoryId: 'pharmacy-vitamins',
    name: 'Multivitamin Daily Formula',
    brand: "Grande Pharmacie de La Corne d'Afrique",
    description:
      'General wellness product seeded from a real Djibouti pharmacy identity.',
    price: 11.99,
    originalPrice: null,
    rating: 4.1,
    reviewCount: 5,
    dosage: '1 tablet daily',
    packageSize: '30 Tablets',
    requiresPrescription: false,
    imageUrlsJson: [],
    colorsJson: [],
    sizesJson: [],
    tagsJson: ['Wellness'],
    featuresJson: ['Daily support'],
    badge: null,
    inStock: true,
    isOrganic: false,
    metadata: { sourceBusiness: "Grande Pharmacie de La Corne d'Afrique", sourcingNote: 'Medicine assortment is curated because live pharmacy inventory is not published online.' },
  },
  {
    id: 'm9',
    moduleType: ModuleType.PHARMACY,
    categoryId: 'pharmacy-pain-relief',
    name: 'Diclofenac Gel',
    brand: 'Independence Pharmacy',
    description:
      'Topical pain-relief item seeded for a broader Djibouti pharmacy assortment.',
    price: 8.99,
    originalPrice: null,
    rating: 4.0,
    reviewCount: 4,
    dosage: 'Apply thin layer 3 times daily',
    packageSize: '50g',
    requiresPrescription: false,
    imageUrlsJson: [],
    colorsJson: [],
    sizesJson: [],
    tagsJson: ['Topical'],
    featuresJson: ['Muscle support', 'Joint comfort'],
    badge: null,
    inStock: true,
    isOrganic: false,
    metadata: { sourceBusiness: 'Independence Pharmacy', sourcingNote: 'Medicine assortment is curated because live pharmacy inventory is not published online.' },
  },
  {
    id: 'm10',
    moduleType: ModuleType.PHARMACY,
    categoryId: 'pharmacy-cold-flu',
    name: 'Children Cough Syrup',
    brand: 'Pharmacie Para',
    description:
      'Pediatric cold-season item seeded for Djibouti pharmacy discovery flows.',
    price: 6.5,
    originalPrice: null,
    rating: 4.2,
    reviewCount: 3,
    dosage: '5ml as directed',
    packageSize: '100ml',
    requiresPrescription: false,
    imageUrlsJson: [],
    colorsJson: [],
    sizesJson: [],
    tagsJson: ['Pediatric'],
    featuresJson: ['Soothing syrup'],
    badge: null,
    inStock: true,
    isOrganic: false,
    metadata: { sourceBusiness: 'Pharmacie Para', sourcingNote: 'Medicine assortment is curated because live pharmacy inventory is not published online.' },
  },
  {
    id: 'm11',
    moduleType: ModuleType.PHARMACY,
    categoryId: 'pharmacy-vitamins',
    name: 'Omega 3 Capsules',
    brand: "Pharmacie De l'OCEAN Indien",
    description:
      'Supplement item attached to a real pharmacy listing in Djibouti City.',
    price: 13.25,
    originalPrice: null,
    rating: 4.1,
    reviewCount: 4,
    dosage: '1 capsule daily',
    packageSize: '30 Capsules',
    requiresPrescription: false,
    imageUrlsJson: [],
    colorsJson: [],
    sizesJson: [],
    tagsJson: ['Supplement'],
    featuresJson: ['Daily omega support'],
    badge: null,
    inStock: true,
    isOrganic: false,
    metadata: { sourceBusiness: "Pharmacie De l'OCEAN Indien", sourcingNote: 'Medicine assortment is curated because live pharmacy inventory is not published online.' },
  },
  {
    id: 'm12',
    moduleType: ModuleType.PHARMACY,
    categoryId: 'pharmacy-pain-relief',
    name: 'Aspirin 100mg',
    brand: 'Pharmacie de la mer rouge',
    description:
      'Additional analgesic entry for wider Djibouti pharmacy browsing.',
    price: 5.25,
    originalPrice: null,
    rating: 4.0,
    reviewCount: 4,
    dosage: 'Use as directed by pharmacist',
    packageSize: '30 Tablets',
    requiresPrescription: false,
    imageUrlsJson: [],
    colorsJson: [],
    sizesJson: [],
    tagsJson: ['Classic'],
    featuresJson: ['Pain relief'],
    badge: null,
    inStock: true,
    isOrganic: false,
    metadata: { sourceBusiness: 'Pharmacie de la mer rouge', sourcingNote: 'Medicine assortment is curated because live pharmacy inventory is not published online.' },
  },
  {
    id: 'm13',
    moduleType: ModuleType.PHARMACY,
    categoryId: 'pharmacy-vitamins',
    name: 'Magnesium B6',
    brand: 'Pharmacie Principale',
    description:
      'Supplement item tied to Pharmacie Principale on Rue d Ethiopie in La Plaine.',
    price: 9.75,
    originalPrice: null,
    rating: 4.3,
    reviewCount: 2,
    dosage: '1 tablet daily',
    packageSize: '30 Tablets',
    requiresPrescription: false,
    imageUrlsJson: [],
    colorsJson: [],
    sizesJson: [],
    tagsJson: ['La Plaine'],
    featuresJson: ['Daily mineral support'],
    badge: null,
    inStock: true,
    isOrganic: false,
    metadata: { sourceBusiness: 'Pharmacie Principale', sourcingNote: 'Medicine assortment is curated because live pharmacy inventory is not published online.' },
  },
  {
    id: 'm14',
    moduleType: ModuleType.PHARMACY,
    categoryId: 'pharmacy-pain-relief',
    name: 'Naproxen 250mg',
    brand: 'Pharmacie polyclinique nawil',
    description:
      'Pain-relief entry linked to the Plateau du Serpent pharmacy corridor in Djibouti City.',
    price: 7.95,
    originalPrice: null,
    rating: 4.1,
    reviewCount: 4,
    dosage: '1 tablet after meals as advised',
    packageSize: '20 Tablets',
    requiresPrescription: false,
    imageUrlsJson: [],
    colorsJson: [],
    sizesJson: [],
    tagsJson: ['Plateau du Serpent'],
    featuresJson: ['Pain and inflammation support'],
    badge: '24h',
    inStock: true,
    isOrganic: false,
    metadata: { sourceBusiness: 'Pharmacie polyclinique nawil', sourcingNote: 'Medicine assortment is curated because live pharmacy inventory is not published online.' },
  },
  {
    id: 'm15',
    moduleType: ModuleType.PHARMACY,
    categoryId: 'pharmacy-cold-flu',
    name: 'Saline Nasal Drops',
    brand: 'Pharmacie Avicenne',
    description:
      'Cold-care item seeded for the Avicenne pharmacy identity to strengthen neighborhood pharmacy variety.',
    price: 5.5,
    originalPrice: null,
    rating: 3.9,
    reviewCount: 3,
    dosage: 'Use as needed',
    packageSize: '30ml',
    requiresPrescription: false,
    imageUrlsJson: [],
    colorsJson: [],
    sizesJson: [],
    tagsJson: ['Neighborhood pharmacy'],
    featuresJson: ['Gentle saline support'],
    badge: null,
    inStock: true,
    isOrganic: false,
    metadata: { sourceBusiness: 'Pharmacie Avicenne', sourcingNote: 'Medicine assortment is curated because live pharmacy inventory is not published online.' },
  },
] as const;

export const djiboutiDoctors = [
  {
    id: 'd1',
    name: 'Som Clinique et Centre de Diagnostic',
    specialty: 'Multi-Specialty Clinic',
    providerType: 'CLINIC',
    rating: 4.5,
    reviewCount: 14,
    experience: 'Established local clinic',
    consultationFee: 35,
    isAvailable: true,
    isSignedUp: true,
    about:
      'Som Clinique is publicly listed with diagnostics and multi-specialty care in Djibouti City.',
    location: 'Rue d Athenes, La Plaine, Djibouti City',
    contactPhone: '+25321335015',
    contactWhatsApp: '+25377731515',
    languagesJson: ['French', 'Arabic', 'Somali'],
    servicesJson: ['General consultation', 'Laboratory', 'Ultrasound', 'Diagnostic imaging'],
    careModesJson: ['Clinic Visit'],
    workingHoursJson: {
      weekdays: '08:00 AM - 06:00 PM',
      saturday: '08:00 AM - 01:00 PM',
      sunday: 'Closed',
    },
  },
  {
    id: 'd2',
    name: 'Cabinet Pediatrie Emma Acina',
    specialty: 'Pediatrics',
    providerType: 'DOCTOR',
    rating: 4.6,
    reviewCount: 8,
    experience: 'Pediatric practice',
    consultationFee: 30,
    isAvailable: true,
    isSignedUp: true,
    about:
      'Pediatric clinic in Djibouti focused on child consultations, growth follow-up, and everyday pediatric care.',
    location: 'Central Djibouti City, near La Plaine',
    contactPhone: '+25377845494',
    contactWhatsApp: '+25377845494',
    languagesJson: ['French', 'Somali', 'Arabic'],
    servicesJson: ['Child consultation', 'Pediatric follow-up', 'Growth monitoring'],
    careModesJson: ['Clinic Visit'],
    workingHoursJson: {
      weekdays: '09:00 AM - 05:00 PM',
      saturday: '09:00 AM - 12:00 PM',
      sunday: 'Closed',
    },
  },
  {
    id: 'd3',
    name: 'Clinique Le Heron',
    specialty: 'General Medicine',
    providerType: 'CLINIC',
    rating: 4.3,
    reviewCount: 11,
    experience: 'Community clinic',
    consultationFee: 28,
    isAvailable: true,
    isSignedUp: true,
    about:
      'Clinique Le Heron is a Djibouti medical facility used here for everyday family and walk-in care.',
    location: 'Heron area, Boulevard de Strasbourg, La Plaine, Djibouti City',
    contactPhone: '+25321345513',
    contactWhatsApp: '+25321345513',
    languagesJson: ['French', 'Arabic'],
    servicesJson: ['General consultation', 'Family medicine', 'Basic diagnostics'],
    careModesJson: ['Clinic Visit'],
    workingHoursJson: {
      weekdays: '08:30 AM - 05:30 PM',
      saturday: '09:00 AM - 01:00 PM',
      sunday: 'Closed',
    },
  },
  {
    id: 'd4',
    name: 'Clinique Dentaire Dr Nasihe Fathi',
    specialty: 'Dentistry',
    providerType: 'DOCTOR',
    rating: 4.7,
    reviewCount: 16,
    experience: 'Dental practice',
    consultationFee: 32,
    isAvailable: true,
    isSignedUp: true,
    about:
      'Dental clinic listing in Djibouti with preventive dental care, tooth repair, and routine oral consultations.',
    location: 'Rue d Ethiopie, La Plaine, Djibouti City',
    contactPhone: '+25321356769',
    contactWhatsApp: '+25321356769',
    languagesJson: ['French', 'Arabic'],
    servicesJson: ['Dental consultation', 'Scaling', 'Fillings', 'Oral care advice'],
    careModesJson: ['Clinic Visit'],
    workingHoursJson: {
      weekdays: '09:00 AM - 06:00 PM',
      saturday: '09:00 AM - 01:00 PM',
      sunday: 'Closed',
    },
  },
  {
    id: 'd5',
    name: 'Djibouti Medical Center',
    specialty: 'General and Diagnostic Care',
    providerType: 'CLINIC',
    rating: 4.4,
    reviewCount: 9,
    experience: 'Modern medical center',
    consultationFee: 34,
    isAvailable: true,
    isSignedUp: true,
    about:
      'Djibouti Medical Center is a local clinical provider used here for outpatient consultations and diagnostics.',
    location: 'IFI Akhiro, Quartier 7 Sud, Djibouti City',
    contactPhone: '+25321350462',
    contactWhatsApp: '+25321350462',
    languagesJson: ['French', 'Arabic', 'English'],
    servicesJson: ['General consultation', 'Diagnostics', 'Checkups'],
    careModesJson: ['Clinic Visit'],
    workingHoursJson: {
      weekdays: '08:00 AM - 06:00 PM',
      saturday: '08:30 AM - 01:00 PM',
      sunday: 'Closed',
    },
  },
  {
    id: 'd9',
    name: 'Dr. Nicholas Georgalis',
    specialty: 'General Practice',
    providerType: 'DOCTOR',
    rating: 3.5,
    reviewCount: 10,
    experience: 'Physician and surgeon listing',
    consultationFee: 27,
    isAvailable: true,
    isSignedUp: true,
    about:
      'Doctor listing surfaced under physicians and surgeons in Djibouti City and used for general-practice coverage.',
    location: 'Unnamed Road, central Djibouti City',
    contactPhone: '+25321353859',
    contactWhatsApp: '+25321353859',
    languagesJson: ['English', 'French'],
    servicesJson: ['General consultation', 'Routine checkup'],
    careModesJson: ['Clinic Visit'],
    workingHoursJson: {
      weekdays: '09:00 AM - 05:00 PM',
      saturday: '09:00 AM - 12:00 PM',
      sunday: 'Closed',
    },
  },
  {
    id: 'd10',
    name: 'Clinique Avicenne',
    specialty: 'General and Family Medicine',
    providerType: 'CLINIC',
    rating: 4.2,
    reviewCount: 7,
    experience: 'Private clinic',
    consultationFee: 29,
    isAvailable: true,
    isSignedUp: true,
    about:
      'Djibouti clinic identity used here for family medicine, routine consultations, and everyday outpatient care.',
    location: 'La Plaine, Djibouti City',
    contactPhone: '+25321354141',
    contactWhatsApp: '+25321354141',
    languagesJson: ['French', 'Arabic'],
    servicesJson: ['Family medicine', 'Routine consultation', 'Follow-up visits'],
    careModesJson: ['Clinic Visit'],
    workingHoursJson: {
      weekdays: '08:30 AM - 05:30 PM',
      saturday: '09:00 AM - 01:00 PM',
      sunday: 'Closed',
    },
  },
  {
    id: 'd11',
    name: 'Cabinet Medical Dr. Mohamed Abdourahman',
    specialty: 'Internal Medicine',
    providerType: 'DOCTOR',
    rating: 4.3,
    reviewCount: 6,
    experience: 'Private practice',
    consultationFee: 33,
    isAvailable: true,
    isSignedUp: true,
    about:
      'Private medical practice in Djibouti used to broaden specialist and doctor coverage inside the app.',
    location: 'Central Djibouti City',
    contactPhone: '+25321352158',
    contactWhatsApp: '+25321352158',
    languagesJson: ['French', 'Arabic'],
    servicesJson: ['Internal medicine', 'Adult consultation', 'Medical follow-up'],
    careModesJson: ['Clinic Visit'],
    workingHoursJson: {
      weekdays: '09:00 AM - 05:00 PM',
      saturday: '09:00 AM - 12:00 PM',
      sunday: 'Closed',
    },
  },
  {
    id: 'd12',
    name: 'FK Medical Polyclinic',
    specialty: 'Polyclinic',
    providerType: 'CLINIC',
    rating: 4.4,
    reviewCount: 8,
    experience: 'Polyclinic care',
    consultationFee: 31,
    isAvailable: true,
    isSignedUp: true,
    about:
      'Multi-doctor clinic profile used for broader outpatient and checkup access in the Djibouti medical catalog.',
    location: 'Djibouti City center',
    contactPhone: '+25321358080',
    contactWhatsApp: '+25321358080',
    languagesJson: ['French', 'Somali', 'Arabic'],
    servicesJson: ['General medicine', 'Polyclinic care', 'Diagnostics'],
    careModesJson: ['Clinic Visit'],
    workingHoursJson: {
      weekdays: '08:00 AM - 06:00 PM',
      saturday: '08:30 AM - 01:00 PM',
      sunday: 'Closed',
    },
  },
  {
    id: 'd13',
    name: 'Clinique Acina',
    specialty: 'Women and Family Care',
    providerType: 'CLINIC',
    rating: 4.5,
    reviewCount: 7,
    experience: 'Community clinic',
    consultationFee: 30,
    isAvailable: true,
    isSignedUp: true,
    about:
      'Local clinic identity used to broaden family-care and womens-health style clinic browsing in Djibouti.',
    location: 'Djibouti City, community-care corridor',
    contactPhone: '+25377845494',
    contactWhatsApp: '+25377845494',
    languagesJson: ['French', 'Arabic', 'Somali'],
    servicesJson: ['Family care', 'Women consultation', 'Clinic follow-up'],
    careModesJson: ['Clinic Visit'],
    workingHoursJson: {
      weekdays: '09:00 AM - 05:00 PM',
      saturday: '09:00 AM - 12:00 PM',
      sunday: 'Closed',
    },
  },
  {
    id: 'd14',
    name: 'Clinical Aden',
    specialty: 'Hospital Care',
    providerType: 'CLINIC',
    rating: 4.3,
    reviewCount: 41,
    experience: 'Well-reviewed clinic',
    consultationFee: 36,
    isAvailable: true,
    isSignedUp: true,
    about:
      'Clinical Aden is a publicly listed hospital-style clinic in Djibouti used to expand trusted care options.',
    location: 'La Plaine, Djibouti City',
    contactPhone: '+25321253232',
    contactWhatsApp: '+25321253232',
    languagesJson: ['French', 'Arabic'],
    servicesJson: ['General consultation', 'Hospital care', 'Checkups'],
    careModesJson: ['Clinic Visit'],
    workingHoursJson: { weekdays: '08:00 AM - 06:00 PM', saturday: '08:30 AM - 01:00 PM', sunday: 'Closed' },
  },
  {
    id: 'd15',
    name: 'Sovereign Djibouti Medical Services',
    specialty: 'Medical Clinic',
    providerType: 'CLINIC',
    rating: 4.1,
    reviewCount: 5,
    experience: 'Medical clinic listing',
    consultationFee: 32,
    isAvailable: true,
    isSignedUp: true,
    about:
      'SDMS is listed in Djibouti as a medical clinic and is used to widen outpatient clinic availability.',
    location: 'La Plaine, Djibouti City',
    contactPhone: '+25321352585',
    contactWhatsApp: '+25321352585',
    languagesJson: ['English', 'French'],
    servicesJson: ['Clinic consultation', 'Medical review', 'Follow-up care'],
    careModesJson: ['Clinic Visit'],
    workingHoursJson: { weekdays: '09:00 AM - 05:00 PM', saturday: '09:00 AM - 12:00 PM', sunday: 'Closed' },
  },
  {
    id: 'd16',
    name: 'DJIB Medic',
    specialty: 'General Medical Practice',
    providerType: 'CLINIC',
    rating: 4.0,
    reviewCount: 4,
    experience: 'Local health practice',
    consultationFee: 29,
    isAvailable: true,
    isSignedUp: true,
    about:
      'DJIB Medic is a local health listing used to broaden general medical access in the app.',
    location: 'Lot 52 53 54 BP 2737, Quartier 7 Sud, Djibouti Ville',
    contactPhone: '+25321350462',
    contactWhatsApp: '+25321350462',
    languagesJson: ['French', 'Arabic'],
    servicesJson: ['General medicine', 'Routine consultation'],
    careModesJson: ['Clinic Visit'],
    workingHoursJson: { weekdays: '08:30 AM - 05:30 PM', saturday: '09:00 AM - 12:00 PM', sunday: 'Closed' },
  },
  {
    id: 'd17',
    name: "Dentist's Surgery of Djibouti",
    specialty: 'Dentistry',
    providerType: 'DOCTOR',
    rating: 4.1,
    reviewCount: 4,
    experience: 'Dental practice',
    consultationFee: 34,
    isAvailable: true,
    isSignedUp: true,
    about:
      'Dental surgery listing used to make the Djibouti medical section feel broader and more practical.',
    location: 'Immeuble Bouche, central Djibouti Ville',
    contactPhone: '+25321355278',
    contactWhatsApp: '+25321355278',
    languagesJson: ['French', 'Arabic'],
    servicesJson: ['Dental consultation', 'Oral care', 'Routine treatment'],
    careModesJson: ['Clinic Visit'],
    workingHoursJson: { weekdays: '09:00 AM - 06:00 PM', saturday: '09:00 AM - 01:00 PM', sunday: 'Closed' },
  },
  {
    id: 'd18',
    name: 'Military Hospital',
    specialty: 'Hospital Care',
    providerType: 'CLINIC',
    rating: 3.8,
    reviewCount: 2,
    experience: 'Hospital facility',
    consultationFee: 38,
    isAvailable: true,
    isSignedUp: false,
    about:
      'Military Hospital is a publicly listed hospital in Djibouti and is included to widen institutional care coverage.',
    location: 'Boûl’aws, Djibouti City',
    contactPhone: '+25321345180',
    contactWhatsApp: '+25321345180',
    languagesJson: ['French', 'Arabic'],
    servicesJson: ['Hospital consultation', 'Emergency orientation', 'General care'],
    careModesJson: ['Clinic Visit'],
    workingHoursJson: { weekdays: '08:00 AM - 06:00 PM', saturday: '08:00 AM - 12:00 PM', sunday: 'Emergency only' },
  },
] as const;

export const djiboutiRestaurants = [
  {
    id: 'r1',
    name: 'Melting Pot',
    cuisine: 'International, Grill, Sushi',
    rating: 4.5,
    reviewCount: 38,
    deliveryTime: '25-35',
    deliveryFee: 2.5,
    imageUrl: null,
    isOpen: true,
    distanceKm: 2.4,
    tagsJson: ['Japanese grill', 'Dinner spot', 'Djibouti City'],
  },
  {
    id: 'r2',
    name: 'La Chaumiere',
    cuisine: 'French, European',
    rating: 4.0,
    reviewCount: 69,
    deliveryTime: '30-40',
    deliveryFee: 2,
    imageUrl: null,
    isOpen: true,
    distanceKm: 1.8,
    tagsJson: ['French', 'Bistro', 'Popular'],
  },
  {
    id: 'r3',
    name: 'Kokeb',
    cuisine: 'African, Ethiopian',
    rating: 4.5,
    reviewCount: 21,
    deliveryTime: '20-30',
    deliveryFee: 1.5,
    imageUrl: null,
    isOpen: true,
    distanceKm: 3.1,
    tagsJson: ['Ethiopian', 'African', 'Shared plates'],
  },
  {
    id: 'r4',
    name: 'Mukbassa Central Chez Youssouf',
    cuisine: 'Djiboutian, Breakfast',
    rating: 4.5,
    reviewCount: 10,
    deliveryTime: '15-25',
    deliveryFee: 1,
    imageUrl: null,
    isOpen: true,
    distanceKm: 2.7,
    tagsJson: ['Local favorite', 'Breakfast', 'Traditional'],
  },
  {
    id: 'r5',
    name: 'Kuriftu Lounge Djibouti',
    cuisine: 'Lounge, International',
    rating: 4.0,
    reviewCount: 9,
    deliveryTime: '30-45',
    deliveryFee: 3,
    imageUrl: null,
    isOpen: true,
    distanceKm: 4.5,
    tagsJson: ['Lounge', 'Sea view', 'Dinner'],
  },
  {
    id: 'r6',
    name: 'Cafe de la Gare',
    cuisine: 'French, Cafe',
    rating: 4.0,
    reviewCount: 54,
    deliveryTime: '20-30',
    deliveryFee: 1.8,
    imageUrl: null,
    isOpen: true,
    distanceKm: 1.4,
    tagsJson: ['Cafe', 'French', 'Classic'],
  },
  {
    id: 'r7',
    name: 'Le Pizzaiollo',
    cuisine: 'Italian, Pizza',
    rating: 4.0,
    reviewCount: 41,
    deliveryTime: '25-35',
    deliveryFee: 2.2,
    imageUrl: null,
    isOpen: true,
    distanceKm: 2.2,
    tagsJson: ['Pizza', 'Italian', 'Casual'],
  },
  {
    id: 'r8',
    name: 'Kingdom Of Sheba Restaurant',
    cuisine: 'Arabic, Yemeni',
    rating: 4.5,
    reviewCount: 2,
    deliveryTime: '20-30',
    deliveryFee: 1.6,
    imageUrl: null,
    isOpen: true,
    distanceKm: 2.0,
    tagsJson: ['Arabic', 'Yemeni', 'Quick bites'],
  },
  {
    id: 'r9',
    name: 'Restaurant Le Tamara',
    cuisine: 'Seafood, African',
    rating: 4.0,
    reviewCount: 2,
    deliveryTime: '30-40',
    deliveryFee: 2.4,
    imageUrl: null,
    isOpen: true,
    distanceKm: 3.8,
    tagsJson: ['Seafood', 'African', 'Fish'],
  },
  {
    id: 'r10',
    name: 'Sixteen Eleven Kitchen',
    cuisine: 'African, Barbecue',
    rating: 4.0,
    reviewCount: 1,
    deliveryTime: '20-30',
    deliveryFee: 1.9,
    imageUrl: null,
    isOpen: true,
    distanceKm: 2.6,
    tagsJson: ['Barbecue', 'Juices', 'African'],
  },
  {
    id: 'r11',
    name: 'Bankouale',
    cuisine: 'Barbecue, Grill, Seafood',
    rating: 4.9,
    reviewCount: 25,
    deliveryTime: '30-40',
    deliveryFee: 2.8,
    imageUrl: null,
    isOpen: true,
    distanceKm: 2.2,
    tagsJson: ['Seafood', 'Grill', 'Top rated'],
  },
  {
    id: 'r12',
    name: 'La Fontaine',
    cuisine: 'African, Ethiopian',
    rating: 3.8,
    reviewCount: 58,
    deliveryTime: '20-30',
    deliveryFee: 1.7,
    imageUrl: null,
    isOpen: true,
    distanceKm: 0.9,
    tagsJson: ['Ethiopian', 'Terrace', 'Casual'],
  },
  {
    id: 'r13',
    name: 'La Mer Rouge',
    cuisine: 'French, Japanese, Seafood',
    rating: 4.1,
    reviewCount: 166,
    deliveryTime: '30-45',
    deliveryFee: 3,
    imageUrl: null,
    isOpen: true,
    distanceKm: 2.1,
    tagsJson: ['Seafood', 'French', 'Japanese'],
  },
  {
    id: 'r14',
    name: 'Saba',
    cuisine: 'African, Seafood',
    rating: 4.0,
    reviewCount: 84,
    deliveryTime: '25-35',
    deliveryFee: 2.2,
    imageUrl: null,
    isOpen: true,
    distanceKm: 1.2,
    tagsJson: ['Yemeni fish', 'Seafood', 'Hidden gem'],
  },
  {
    id: 'r15',
    name: 'Sings Restaurant',
    cuisine: 'Indian',
    rating: 4.1,
    reviewCount: 39,
    deliveryTime: '25-35',
    deliveryFee: 2.1,
    imageUrl: null,
    isOpen: true,
    distanceKm: 1.9,
    tagsJson: ['Indian', 'Traditional', 'Popular'],
  },
  {
    id: 'r16',
    name: "HanCake's",
    cuisine: 'Buffet, Cafe',
    rating: 4.5,
    reviewCount: 51,
    deliveryTime: '20-30',
    deliveryFee: 1.9,
    imageUrl: null,
    isOpen: true,
    distanceKm: 1.1,
    tagsJson: ['Rue de Rome', 'La Plaine', 'Buffet'],
  },
  {
    id: 'r17',
    name: 'Restaurant La Terrasse',
    cuisine: 'Ethiopian, Local',
    rating: 4.2,
    reviewCount: 39,
    deliveryTime: '20-30',
    deliveryFee: 1.7,
    imageUrl: null,
    isOpen: true,
    distanceKm: 1.3,
    tagsJson: ["Rue d'Ethiopie", 'La Plaine', 'Local favorite'],
  },
] as const;

export const djiboutiRestaurantMenuCategories = [
  { id: 'r1-signatures', restaurantId: 'r1', name: 'Signatures', sortOrder: 1 },
  { id: 'r1-rolls', restaurantId: 'r1', name: 'Rolls & Plates', sortOrder: 2 },
  { id: 'r2-mains', restaurantId: 'r2', name: 'French Classics', sortOrder: 1 },
  { id: 'r2-dessert', restaurantId: 'r2', name: 'Desserts', sortOrder: 2 },
  { id: 'r3-shared', restaurantId: 'r3', name: 'Shared Platters', sortOrder: 1 },
  { id: 'r3-grill', restaurantId: 'r3', name: 'Hot Dishes', sortOrder: 2 },
  { id: 'r4-breakfast', restaurantId: 'r4', name: 'Breakfast', sortOrder: 1 },
  { id: 'r4-drinks', restaurantId: 'r4', name: 'Drinks', sortOrder: 2 },
  { id: 'r5-mains', restaurantId: 'r5', name: 'Lounge Mains', sortOrder: 1 },
  { id: 'r5-drinks', restaurantId: 'r5', name: 'Mocktails', sortOrder: 2 },
  { id: 'r6-cafe', restaurantId: 'r6', name: 'Cafe Plates', sortOrder: 1 },
  { id: 'r6-desserts', restaurantId: 'r6', name: 'Pastry & Dessert', sortOrder: 2 },
  { id: 'r7-pizza', restaurantId: 'r7', name: 'Pizzas', sortOrder: 1 },
  { id: 'r7-pasta', restaurantId: 'r7', name: 'Pasta', sortOrder: 2 },
  { id: 'r8-grill', restaurantId: 'r8', name: 'Arabic Specials', sortOrder: 1 },
  { id: 'r8-drinks', restaurantId: 'r8', name: 'Drinks', sortOrder: 2 },
  { id: 'r9-seafood', restaurantId: 'r9', name: 'Seafood', sortOrder: 1 },
  { id: 'r10-bbq', restaurantId: 'r10', name: 'BBQ Plates', sortOrder: 1 },
  { id: 'r11-grill', restaurantId: 'r11', name: 'Sea Grill', sortOrder: 1 },
  { id: 'r12-platters', restaurantId: 'r12', name: 'African Plates', sortOrder: 1 },
  { id: 'r13-seafood', restaurantId: 'r13', name: 'Seafood Signatures', sortOrder: 1 },
  { id: 'r14-seafood', restaurantId: 'r14', name: 'Yemeni Fish', sortOrder: 1 },
  { id: 'r15-indian', restaurantId: 'r15', name: 'Indian Classics', sortOrder: 1 },
  { id: 'r16-buffet', restaurantId: 'r16', name: 'Buffet Plates', sortOrder: 1 },
  { id: 'r17-ethiopian', restaurantId: 'r17', name: 'Ethiopian Plates', sortOrder: 1 },
] as const;

export const djiboutiRestaurantMenuItems = [
  {
    id: 'food-m1',
    categoryId: 'r1-signatures',
    name: 'Teriyaki Chicken Bowl',
    description: 'Representative signature bowl inspired by Melting Pot grill and Asian-fusion positioning.',
    price: 14.99,
    imageUrl: null,
    isPopular: true,
    isAvailable: true,
    customizationsJson: ['Extra sauce', 'No onions'],
  },
  {
    id: 'food-m2',
    categoryId: 'r1-rolls',
    name: 'Salmon Crunch Roll',
    description: 'Curated sushi-style menu item for the Melting Pot seed catalog.',
    price: 16.5,
    imageUrl: null,
    isPopular: true,
    isAvailable: true,
    customizationsJson: ['Extra wasabi'],
  },
  {
    id: 'food-m3',
    categoryId: 'r2-mains',
    name: 'Steak Frites',
    description: 'French bistro staple used as a representative La Chaumiere main dish.',
    price: 19.99,
    imageUrl: null,
    isPopular: true,
    isAvailable: true,
    customizationsJson: ['Medium rare', 'Pepper sauce'],
  },
  {
    id: 'food-m4',
    categoryId: 'r2-dessert',
    name: 'Creme Caramel',
    description: 'Classic dessert seeded for La Chaumiere.',
    price: 6.5,
    imageUrl: null,
    isPopular: false,
    isAvailable: true,
    customizationsJson: [],
  },
  {
    id: 'food-m5',
    categoryId: 'r3-shared',
    name: 'Mixed Injera Platter',
    description: 'Representative Ethiopian-style shared platter for Kokeb.',
    price: 17.99,
    imageUrl: null,
    isPopular: true,
    isAvailable: true,
    customizationsJson: ['Mild spice', 'Extra vegetables'],
  },
  {
    id: 'food-m6',
    categoryId: 'r3-grill',
    name: 'Doro Wat Plate',
    description: 'Seeded hot dish inspired by East African and Ethiopian cuisine.',
    price: 15.25,
    imageUrl: null,
    isPopular: false,
    isAvailable: true,
    customizationsJson: ['Extra injera'],
  },
  {
    id: 'food-m7',
    categoryId: 'r4-breakfast',
    name: 'Mukbassa with Honey',
    description: 'Local breakfast item added for Mukbassa Central Chez Youssouf.',
    price: 5.5,
    imageUrl: null,
    isPopular: true,
    isAvailable: true,
    customizationsJson: ['Extra honey', 'Add cream'],
  },
  {
    id: 'food-m8',
    categoryId: 'r4-drinks',
    name: 'Shaah Cadeys',
    description: 'Sweet spiced tea for a traditional breakfast pairing.',
    price: 2,
    imageUrl: null,
    isPopular: false,
    isAvailable: true,
    customizationsJson: ['Less sugar'],
  },
  {
    id: 'food-m9',
    categoryId: 'r5-mains',
    name: 'Grilled Fish Fillet',
    description: 'Representative lounge-style seafood main for Kuriftu Lounge Djibouti.',
    price: 21.99,
    imageUrl: null,
    isPopular: true,
    isAvailable: true,
    customizationsJson: ['Side salad', 'Rice'],
  },
  {
    id: 'food-m10',
    categoryId: 'r5-drinks',
    name: 'Passion Fruit Cooler',
    description: 'Fruit-forward mocktail used to round out the lounge menu.',
    price: 4.99,
    imageUrl: null,
    isPopular: false,
    isAvailable: true,
    customizationsJson: ['Less ice'],
  },
  {
    id: 'food-m11',
    categoryId: 'r6-cafe',
    name: 'Croque Monsieur',
    description: 'Representative cafe main seeded for Cafe de la Gare.',
    price: 9.5,
    imageUrl: null,
    isPopular: true,
    isAvailable: true,
    customizationsJson: ['Add egg'],
  },
  {
    id: 'food-m12',
    categoryId: 'r6-desserts',
    name: 'Chocolate Eclair',
    description: 'French pastry item used to round out the Cafe de la Gare catalog.',
    price: 3.75,
    imageUrl: null,
    isPopular: false,
    isAvailable: true,
    customizationsJson: [],
  },
  {
    id: 'food-m13',
    categoryId: 'r7-pizza',
    name: 'Margherita Pizza',
    description: 'Representative classic pizza seeded for Le Pizzaiollo.',
    price: 12.99,
    imageUrl: null,
    isPopular: true,
    isAvailable: true,
    customizationsJson: ['Extra cheese', 'Olives'],
  },
  {
    id: 'food-m14',
    categoryId: 'r7-pasta',
    name: 'Penne Arrabbiata',
    description: 'Curated pasta option for the Italian restaurant seed catalog.',
    price: 11.5,
    imageUrl: null,
    isPopular: false,
    isAvailable: true,
    customizationsJson: ['Extra chili'],
  },
  {
    id: 'food-m15',
    categoryId: 'r8-grill',
    name: 'Chicken Mandi Plate',
    description: 'Yemeni-style rice and chicken dish seeded for Kingdom Of Sheba Restaurant.',
    price: 13.5,
    imageUrl: null,
    isPopular: true,
    isAvailable: true,
    customizationsJson: ['Extra sauce'],
  },
  {
    id: 'food-m16',
    categoryId: 'r8-drinks',
    name: 'Mint Lemon Juice',
    description: 'Refreshing juice pairing for Arabic grill dishes.',
    price: 3.25,
    imageUrl: null,
    isPopular: false,
    isAvailable: true,
    customizationsJson: ['Less sugar'],
  },
  {
    id: 'food-m17',
    categoryId: 'r9-seafood',
    name: 'Grilled Red Snapper',
    description: 'Representative seafood plate added for Restaurant Le Tamara.',
    price: 18.75,
    imageUrl: null,
    isPopular: true,
    isAvailable: true,
    customizationsJson: ['Rice', 'Fries'],
  },
  {
    id: 'food-m18',
    categoryId: 'r10-bbq',
    name: 'Mixed BBQ Platter',
    description: 'Seeded barbecue platter for Sixteen Eleven Kitchen.',
    price: 16.99,
    imageUrl: null,
    isPopular: true,
    isAvailable: true,
    customizationsJson: ['Extra sauce', 'Spicy'],
  },
  {
    id: 'food-m19',
    categoryId: 'r11-grill',
    name: 'Charcoal Lobster Plate',
    description: 'Representative seafood grill dish for Bankouale.',
    price: 24.5,
    imageUrl: null,
    isPopular: true,
    isAvailable: true,
    customizationsJson: ['Rice', 'Salad'],
  },
  {
    id: 'food-m20',
    categoryId: 'r12-platters',
    name: 'Ethiopian Veggie Combo',
    description: 'Shared Ethiopian platter seeded for La Fontaine.',
    price: 12.75,
    imageUrl: null,
    isPopular: true,
    isAvailable: true,
    customizationsJson: ['Extra injera'],
  },
  {
    id: 'food-m21',
    categoryId: 'r13-seafood',
    name: 'Seafood Linguine',
    description: 'French-seafood inspired pasta dish added for La Mer Rouge.',
    price: 22.99,
    imageUrl: null,
    isPopular: true,
    isAvailable: true,
    customizationsJson: ['Extra shrimp'],
  },
  {
    id: 'food-m22',
    categoryId: 'r14-seafood',
    name: 'Yemeni Oven Fish',
    description: 'Representative fish specialty for Saba.',
    price: 17.5,
    imageUrl: null,
    isPopular: true,
    isAvailable: true,
    customizationsJson: ['Rice', 'Bread'],
  },
  {
    id: 'food-m23',
    categoryId: 'r15-indian',
    name: 'Chicken Biryani',
    description: 'Classic Indian rice dish seeded for Sings Restaurant.',
    price: 13.25,
    imageUrl: null,
    isPopular: true,
    isAvailable: true,
    customizationsJson: ['Extra raita', 'Spicy'],
  },
  {
    id: 'food-m24',
    categoryId: 'r16-buffet',
    name: "Mini Pastry Buffet Box",
    description: "Representative buffet-and-dessert item for HanCake's on Rue de Rome.",
    price: 8.75,
    imageUrl: null,
    isPopular: true,
    isAvailable: true,
    customizationsJson: ['Mixed selection'],
  },
  {
    id: 'food-m25',
    categoryId: 'r17-ethiopian',
    name: 'Beef Tibs Plate',
    description: 'Representative Ethiopian grill plate for Restaurant La Terrasse on Rue d Ethiopie.',
    price: 14.25,
    imageUrl: null,
    isPopular: true,
    isAvailable: true,
    customizationsJson: ['Extra injera', 'Spicy'],
  },
] as const;

export const djiboutiHotels = [
  {
    id: 'h1',
    name: 'Djibouti Palace Kempinski',
    address: 'Ilot du Heron, Djibouti City',
    city: 'Djibouti',
    rating: 4.4,
    reviewsCount: 387,
    pricePerNight: 245,
    amenitiesJson: ['Pool', 'Spa', 'Beach access', 'Free WiFi', 'Restaurants'],
    description:
      'Luxury waterfront hotel in Djibouti with resort amenities, dining, and conference facilities.',
    imageUrlsJson: [],
  },
  {
    id: 'h2',
    name: 'Ras Dika Hotel',
    address: 'Avenue Mohamed Ali, Djibouti City',
    city: 'Djibouti',
    rating: 4.8,
    reviewsCount: 72,
    pricePerNight: 126,
    amenitiesJson: ['Restaurant', 'Room service', 'Free WiFi', 'Airport access'],
    description:
      'Well-reviewed city hotel used for central-stay bookings in the Djibouti catalog.',
    imageUrlsJson: [],
  },
  {
    id: 'h3',
    name: 'Atlantic Hotel',
    address: 'Rue de Rome, Djibouti City',
    city: 'Djibouti',
    rating: 3.8,
    reviewsCount: 116,
    pricePerNight: 112,
    amenitiesJson: ['Restaurant', 'Free WiFi', 'Airport shuttle', 'Breakfast'],
    description:
      'Central hotel in Djibouti City with restaurant service and practical business-travel amenities.',
    imageUrlsJson: [],
  },
  {
    id: 'h4',
    name: 'Les Acacias Hotel Djibouti',
    address: 'Plateau du Serpent, Djibouti City',
    city: 'Djibouti',
    rating: 3.2,
    reviewsCount: 102,
    pricePerNight: 134,
    amenitiesJson: ['Pool', 'Sea view', 'Restaurant', 'Free WiFi'],
    description:
      'Seafront hotel property in Djibouti, suitable for leisure stays and short city breaks.',
    imageUrlsJson: [],
  },
  {
    id: 'h5',
    name: 'Sheraton Djibouti',
    address: 'Plateau du Serpent, Djibouti City',
    city: 'Djibouti',
    rating: 4.0,
    reviewsCount: 214,
    pricePerNight: 172,
    amenitiesJson: ['Pool', 'Beach access', 'Restaurant', 'Business facilities'],
    description:
      'International-brand beachfront hotel seeded for broader Djibouti hotel coverage.',
    imageUrlsJson: [],
  },
  {
    id: 'h6',
    name: 'Ayla Grand Hotel',
    address: 'Avenue 26, Djibouti City',
    city: 'Djibouti',
    rating: 4.1,
    reviewsCount: 88,
    pricePerNight: 118,
    amenitiesJson: ['Restaurant', 'Free WiFi', 'Airport shuttle', 'Breakfast'],
    description:
      'Modern city-stay hotel profile added to improve mid-range hotel options in the catalog.',
    imageUrlsJson: [],
  },
  {
    id: 'h7',
    name: "Hotel Residence de l'Europe",
    address: 'Place Menelik, Djibouti City',
    city: 'Djibouti',
    rating: 3.7,
    reviewsCount: 73,
    pricePerNight: 94,
    amenitiesJson: ['Central location', 'Restaurant', 'Free WiFi'],
    description:
      'Historic city-center stay option seeded for practical, lower-price hotel browsing.',
    imageUrlsJson: [],
  },
  {
    id: 'h8',
    name: 'Comfort Hotel',
    address: 'Djibouti City Center, Djibouti',
    city: 'Djibouti',
    rating: 3.9,
    reviewsCount: 49,
    pricePerNight: 89,
    amenitiesJson: ['Breakfast', 'Free WiFi', 'Air-conditioned rooms'],
    description:
      'Comfort-focused city hotel added for budget-to-midrange lodging coverage.',
    imageUrlsJson: [],
  },
  {
    id: 'h9',
    name: 'Capital Hotel Djibouti',
    address: 'Djibouti City',
    city: 'Djibouti',
    rating: 3.7,
    reviewsCount: 9,
    pricePerNight: 97,
    amenitiesJson: ['Mid-range rooms', 'Central stay', 'WiFi'],
    description:
      'Small-hotel option in Djibouti added for broader mid-range lodging coverage.',
    imageUrlsJson: [],
  },
  {
    id: 'h10',
    name: 'Hotel Rayan Djibouti',
    address: 'Boulevard De La Republique, Djibouti',
    city: 'Djibouti',
    rating: 3.5,
    reviewsCount: 6,
    pricePerNight: 78,
    amenitiesJson: ['Free breakfast', 'WiFi', 'Airport transportation', 'Beach nearby'],
    description:
      'Budget-friendly hotel profile near downtown and the beach, based on TripAdvisor details.',
    imageUrlsJson: [],
  },
  {
    id: 'h11',
    name: 'Lagon Bleu Village',
    address: 'Rue Ras Makonen, Djibouti BP1181',
    city: 'Djibouti',
    rating: 3.4,
    reviewsCount: 15,
    pricePerNight: 142,
    amenitiesJson: ['Private beach', 'Bar', 'Water activities', 'Island bungalows'],
    description:
      'Island resort stay on Moucha Island added to give the hotel module some destination-style variety.',
    imageUrlsJson: [],
  },
  {
    id: 'h12',
    name: 'African Village Hotel',
    address: "BP. 920, Rond Point de l'Aeroport, Djibouti",
    city: 'Djibouti',
    rating: 3.4,
    reviewsCount: 17,
    pricePerNight: 67,
    amenitiesJson: ['Airport access', 'Open-air restaurant', 'WiFi', 'Parking'],
    description:
      'Airport-adjacent hotel listing used for practical and budget-conscious stay options.',
    imageUrlsJson: [],
  },
  {
    id: 'h13',
    name: 'Hotel and restaurantde Djibouti',
    address: 'Boite postale 6353, en face du roundpoint, Avenue 13, La Plaine, Djibouti',
    city: 'Djibouti',
    rating: 4.1,
    reviewsCount: 63,
    pricePerNight: 86,
    amenitiesJson: ['Avenue 13 location', 'Restaurant', 'Neighborhood stay'],
    description:
      'Avenue 13 hotel-and-restaurant property that strengthens dense La Plaine lodging coverage.',
    imageUrlsJson: [],
  },
] as const;

export const djiboutiLaundryServices = [
  {
    id: 'l1',
    name: 'Laundry King Djibouti',
    description: 'Local laundry provider in Djibouti for regular wash and fold orders.',
    price: 14,
    unit: 'per bag',
    iconUrl: 'wash',
    active: true,
  },
  {
    id: 'l2',
    name: 'Rex Laundry Steam Pressing',
    description: 'Steam pressing and garment finishing service in Djibouti City.',
    price: 3.5,
    unit: 'per item',
    iconUrl: 'iron',
    active: true,
  },
  {
    id: 'l3',
    name: 'Eco Pressing',
    description: 'Dry-cleaning and pressing option seeded from Djibouti laundry listings.',
    price: 4.5,
    unit: 'per item',
    iconUrl: 'dry',
    active: true,
  },
  {
    id: 'l4',
    name: 'Djibouti Laundry',
    description: 'General laundry pickup-ready service used for standard household orders.',
    price: 16,
    unit: 'per bag',
    iconUrl: 'wash',
    active: true,
  },
  {
    id: 'l5',
    name: 'Small Laundry',
    description: 'Neighborhood wash-and-fold provider used to expand everyday laundry coverage.',
    price: 12,
    unit: 'per bag',
    iconUrl: 'wash',
    active: true,
  },
  {
    id: 'l6',
    name: 'Self-Service Laundry Main',
    description: 'Self-service and drop-off laundry option in Djibouti City.',
    price: 9,
    unit: 'per load',
    iconUrl: 'wash',
    active: true,
  },
  {
    id: 'l7',
    name: 'Blanchisserie Pressing 2000',
    description: 'Pressing and garment-care laundry service for dresswear and office clothes.',
    price: 4,
    unit: 'per item',
    iconUrl: 'iron',
    active: true,
  },
  {
    id: 'l8',
    name: 'Tango 5',
    description: 'Compact neighborhood laundry option added from local laundry listings.',
    price: 10,
    unit: 'per bag',
    iconUrl: 'wash',
    active: true,
  },
  {
    id: 'l9',
    name: 'Rex Blanchisserie Pressing',
    description: 'Garment-care and pressing service for formal clothes and everyday wear.',
    price: 4.25,
    unit: 'per item',
    iconUrl: 'iron',
    active: true,
  },
  {
    id: 'l10',
    name: 'Blanchisserie Pressing Rex',
    description: 'Additional Rex-branded pressing entry used for broader laundry search coverage.',
    price: 4.25,
    unit: 'per item',
    iconUrl: 'dry',
    active: true,
  },
] as const;

export const djiboutiHomeServiceCategories = [
  {
    id: 'hs-house-help',
    name: 'House Help',
    slug: 'house-help',
    description:
      'On-demand house help for daily chores, kitchen cleanup, laundry, and recurring support.',
    iconKey: 'house_help',
    colorHex: '#1A9A77',
    sortOrder: 1,
    active: true,
  },
  {
    id: 'hs-cleaning',
    name: 'Home Cleaning',
    slug: 'cleaning',
    description: 'Routine, deep, and move-in cleaning for apartments and houses.',
    iconKey: 'cleaning',
    colorHex: '#0F9D92',
    sortOrder: 2,
    active: true,
  },
  {
    id: 'hs-plumbing',
    name: 'Plumbing',
    slug: 'plumbing',
    description: 'Leaks, fittings, drainage, and urgent plumbing help.',
    iconKey: 'plumbing',
    colorHex: '#3B82F6',
    sortOrder: 3,
    active: true,
  },
  {
    id: 'hs-electrical',
    name: 'Electrical',
    slug: 'electrical',
    description: 'Installations, repairs, and safe home electrical work.',
    iconKey: 'electrical',
    colorHex: '#F59E0B',
    sortOrder: 4,
    active: true,
  },
  {
    id: 'hs-ac',
    name: 'AC & Cooling',
    slug: 'ac-cooling',
    description: 'AC servicing, gas refill, and cooling-system fixes.',
    iconKey: 'ac',
    colorHex: '#06B6D4',
    sortOrder: 5,
    active: true,
  },
  {
    id: 'hs-beauty',
    name: 'Beauty at Home',
    slug: 'beauty-at-home',
    description: 'Hair, makeup, nails, and self-care professionals at home.',
    iconKey: 'beauty',
    colorHex: '#EC4899',
    sortOrder: 6,
    active: true,
  },
  {
    id: 'hs-handyman',
    name: 'Handyman',
    slug: 'handyman',
    description: 'Furniture assembly, curtain fixing, drilling, and home tasks.',
    iconKey: 'handyman',
    colorHex: '#8B5CF6',
    sortOrder: 7,
    active: true,
  },
] as const;

export const djiboutiHomeServiceProviders = [
  {
    id: 'hsp-20',
    categoryId: 'hs-house-help',
    name: 'Pronto House Help Djibouti',
    title: 'Instant House Help Team',
    rating: 4.8,
    reviewCount: 34,
    yearsExperience: 'On-demand domestic operations',
    startingPrice: 13,
    isAvailable: true,
    isVerified: true,
    responseTime: 'Responds in 12 min',
    about:
      'Dedicated house-help team focused on quick dispatch, verified helpers, and recurring support for busy households.',
    location: 'La Plaine and Central Djibouti City',
    contactPhone: '+25377881120',
    servicesJson: [
      'Floor cleaning',
      'Kitchen cleaning',
      'Bathroom cleaning',
      'Dishes',
      'Laundry',
    ],
    highlightsJson: [
      '10-15 min dispatch target',
      'Recurring daily and weekly support',
      'Verified helpers',
    ],
    bookingModesJson: ['Instant Dispatch', 'Scheduled Visit', 'Recurring Plan'],
    availabilityJson: {
      weekdays: '07:00 AM - 10:00 PM',
      saturday: '07:00 AM - 10:00 PM',
      sunday: '08:00 AM - 08:00 PM',
    },
  },
  {
    id: 'hsp-21',
    categoryId: 'hs-house-help',
    name: 'Urban Nadiifa Helpers',
    title: 'Daily Chores and Home Upkeep',
    rating: 4.6,
    reviewCount: 26,
    yearsExperience: 'Neighborhood housekeeping services',
    startingPrice: 12,
    isAvailable: true,
    isVerified: true,
    responseTime: 'Responds in 15 min',
    about:
      'Local helper squad for routine apartment chores, dishwashing, and weekly maintenance support.',
    location: 'Balbala, La Plaine, and Plateau zones',
    contactPhone: '+25377881121',
    servicesJson: [
      'Daily home upkeep',
      'Dishes and kitchen reset',
      'Laundry folding',
      'Surface dusting',
      'Room tidying',
    ],
    highlightsJson: [
      'Recurring plan support',
      'Trusted neighborhood helpers',
      'Flexible shift duration',
    ],
    bookingModesJson: ['Instant Dispatch', 'Scheduled Visit', 'Recurring Plan'],
    availabilityJson: {
      weekdays: '07:30 AM - 09:30 PM',
      saturday: '08:00 AM - 09:00 PM',
      sunday: '08:30 AM - 07:30 PM',
    },
  },
  {
    id: 'hsp-22',
    categoryId: 'hs-house-help',
    name: 'Safa Home Assist',
    title: 'Family House Assistance',
    rating: 4.5,
    reviewCount: 18,
    yearsExperience: 'Residential support service',
    startingPrice: 14,
    isAvailable: true,
    isVerified: true,
    responseTime: 'Responds in 18 min',
    about:
      'Verified home assistants for family households needing predictable support across cleaning, dishes, and laundry.',
    location: 'Haramous and city-center neighborhoods',
    contactPhone: '+25377881122',
    servicesJson: [
      'Full-home touch-up',
      'Laundry sorting and wash prep',
      'Bathroom reset',
      'Kitchen deep touch-up',
      'Bed making',
    ],
    highlightsJson: [
      'House-size based service',
      'Family-friendly support',
      'Reliable weekly staff continuity',
    ],
    bookingModesJson: ['Scheduled Visit', 'Recurring Plan', 'Instant Dispatch'],
    availabilityJson: {
      weekdays: '08:00 AM - 09:00 PM',
      saturday: '08:30 AM - 08:30 PM',
      sunday: '09:00 AM - 06:00 PM',
    },
  },
  {
    id: 'hsp-23',
    categoryId: 'hs-house-help',
    name: 'Nabdaa Quick Help',
    title: 'Express Household Chores',
    rating: 4.4,
    reviewCount: 15,
    yearsExperience: 'Rapid-response home support',
    startingPrice: 11,
    isAvailable: true,
    isVerified: false,
    responseTime: 'Responds in 20 min',
    about:
      'Budget-friendly household support for urgent same-day chores and scheduled maintenance windows.',
    location: 'Djibouti City',
    contactPhone: '+25377881123',
    servicesJson: [
      'Quick room cleaning',
      'Dishes and sink reset',
      'Laundry handling',
      'Trash and utility cleanup',
      'Post-cooking cleanup',
    ],
    highlightsJson: [
      'Entry-level pricing',
      'Express slot availability',
      'Household basics coverage',
    ],
    bookingModesJson: ['Instant Dispatch', 'Scheduled Visit'],
    availabilityJson: {
      weekdays: '07:00 AM - 08:30 PM',
      saturday: '07:30 AM - 08:00 PM',
      sunday: '08:00 AM - 06:00 PM',
    },
  },
  {
    id: 'hsp-1',
    categoryId: 'hs-cleaning',
    name: 'Xtreme Hygiene Solutions Ltd',
    title: 'Cleaning and Hygiene Services',
    rating: 4.5,
    reviewCount: 10,
    yearsExperience: 'Commercial cleaning operator',
    startingPrice: 24,
    isAvailable: true,
    isVerified: true,
    responseTime: 'Responds in 30 min',
    about: 'Local hygiene and cleaning company in Djibouti adapted here for home and office service requests.',
    location: 'La Plaine, Djibouti City',
    contactPhone: '+25377826666',
    servicesJson: ['Deep cleaning', 'Office cleaning', 'Disinfection'],
    highlightsJson: ['Local company', 'Cleaning specialist'],
    bookingModesJson: ['Home Visit'],
    availabilityJson: { weekdays: '08:00 AM - 06:00 PM', saturday: '09:00 AM - 02:00 PM', sunday: 'Closed' },
  },
  {
    id: 'hsp-2',
    categoryId: 'hs-plumbing',
    name: 'Djibsolar',
    title: 'Plumbing and HVAC Installer',
    rating: 4.4,
    reviewCount: 9,
    yearsExperience: 'Building systems provider',
    startingPrice: 28,
    isAvailable: true,
    isVerified: true,
    responseTime: 'Responds in 45 min',
    about: 'Djibsolar is listed for plumbing, heat, and AC installation and is mapped to in-home technical work.',
    location: 'Plateau du Serpent, Djibouti City',
    contactPhone: '+25321350147',
    servicesJson: ['Pipe installation', 'Water fittings', 'Technical inspection'],
    highlightsJson: ['Multi-service firm', 'Technical installations'],
    bookingModesJson: ['Home Visit'],
    availabilityJson: { weekdays: '08:30 AM - 05:30 PM', saturday: '09:00 AM - 01:00 PM', sunday: 'Closed' },
  },
  {
    id: 'hsp-3',
    categoryId: 'hs-electrical',
    name: 'Electricite de Djibouti',
    title: 'Electrical Service Support',
    rating: 4.0,
    reviewCount: 8,
    yearsExperience: 'National power operator',
    startingPrice: 20,
    isAvailable: true,
    isVerified: true,
    responseTime: 'Responds in 1 hr',
    about: 'Mapped into the app as an electrical support option for meter, wiring, and connection guidance.',
    location: 'Quartier 7, Djibouti City',
    contactPhone: '+25321356000',
    servicesJson: ['Electrical inspection', 'Connection support', 'Fault follow-up'],
    highlightsJson: ['Recognized operator', 'Infrastructure expertise'],
    bookingModesJson: ['Home Visit', 'Phone Advice'],
    availabilityJson: { weekdays: '08:00 AM - 05:00 PM', saturday: 'Closed', sunday: 'Closed' },
  },
  {
    id: 'hsp-4',
    categoryId: 'hs-ac',
    name: 'Polyservices',
    title: 'AC and Cooling Technician',
    rating: 4.3,
    reviewCount: 7,
    yearsExperience: 'Cooling systems company',
    startingPrice: 26,
    isAvailable: true,
    isVerified: true,
    responseTime: 'Responds in 40 min',
    about: 'Djibouti cooling and maintenance company adapted for AC service bookings.',
    location: 'Quartier 7, Djibouti City',
    contactPhone: '+25321355220',
    servicesJson: ['AC cleaning', 'Cooling repair', 'Maintenance visit'],
    highlightsJson: ['Cooling specialist', 'Maintenance support'],
    bookingModesJson: ['Home Visit'],
    availabilityJson: { weekdays: '08:30 AM - 06:00 PM', saturday: '09:00 AM - 01:00 PM', sunday: 'Closed' },
  },
  {
    id: 'hsp-5',
    categoryId: 'hs-beauty',
    name: 'SAM Beauty and Spa',
    title: 'Beauty and Wellness',
    rating: 4.6,
    reviewCount: 15,
    yearsExperience: 'Established beauty studio',
    startingPrice: 18,
    isAvailable: true,
    isVerified: true,
    responseTime: 'Responds in 25 min',
    about: 'Beauty and spa business in Djibouti adapted for at-home grooming and event prep requests.',
    location: 'Heron, Djibouti City',
    contactPhone: '+25377416548',
    servicesJson: ['Makeup', 'Hair styling', 'Spa care'],
    highlightsJson: ['Beauty studio', 'Event-ready sessions'],
    bookingModesJson: ['Home Visit'],
    availabilityJson: { weekdays: '10:00 AM - 08:00 PM', saturday: '09:00 AM - 07:00 PM', sunday: '10:00 AM - 04:00 PM' },
  },
  {
    id: 'hsp-6',
    categoryId: 'hs-handyman',
    name: 'Alga Lux',
    title: 'Appliance Repair and Handyman',
    rating: 4.2,
    reviewCount: 6,
    yearsExperience: 'Repair business',
    startingPrice: 17,
    isAvailable: true,
    isVerified: false,
    responseTime: 'Responds in 1 hr',
    about: 'Local repair business mapped to handyman support for household equipment and minor fixes.',
    location: 'Rue de Rome, La Plaine, Djibouti City',
    contactPhone: '+25321354531',
    servicesJson: ['Appliance repair', 'Minor home fixes', 'Equipment checks'],
    highlightsJson: ['Repair-focused', 'Practical household support'],
    bookingModesJson: ['Home Visit'],
    availabilityJson: { weekdays: '08:30 AM - 05:30 PM', saturday: '09:00 AM - 01:00 PM', sunday: 'Closed' },
  },
  {
    id: 'hsp-9',
    categoryId: 'hs-beauty',
    name: 'S and H Beauty Box',
    title: 'Beauty Boutique and Styling',
    rating: 4.4,
    reviewCount: 9,
    yearsExperience: 'Beauty retail and styling',
    startingPrice: 15,
    isAvailable: true,
    isVerified: true,
    responseTime: 'Responds in 35 min',
    about: 'Djibouti beauty business adapted into the app for makeup, styling, and home beauty sessions.',
    location: 'Central Djibouti City',
    contactPhone: '+25377882949',
    servicesJson: ['Makeup session', 'Beauty styling', 'Event prep'],
    highlightsJson: ['Beauty-focused', 'Local boutique'],
    bookingModesJson: ['Home Visit'],
    availabilityJson: { weekdays: '10:00 AM - 08:00 PM', saturday: '10:00 AM - 07:00 PM', sunday: '11:00 AM - 04:00 PM' },
  },
  {
    id: 'hsp-10',
    categoryId: 'hs-cleaning',
    name: 'Clean Pro Djibouti',
    title: 'Residential Cleaning Team',
    rating: 4.3,
    reviewCount: 7,
    yearsExperience: 'Cleaning service listing',
    startingPrice: 20,
    isAvailable: true,
    isVerified: false,
    responseTime: 'Responds in 40 min',
    about: 'Local cleaning-service identity added for apartments, offices, and move-in cleanup requests.',
    location: 'Djibouti City',
    contactPhone: '+25377870001',
    servicesJson: ['Apartment cleaning', 'Office cleanup', 'Move-in refresh'],
    highlightsJson: ['Flexible cleaning slots', 'Household support'],
    bookingModesJson: ['Home Visit'],
    availabilityJson: { weekdays: '08:00 AM - 06:00 PM', saturday: '09:00 AM - 03:00 PM', sunday: 'Closed' },
  },
  {
    id: 'hsp-11',
    categoryId: 'hs-electrical',
    name: 'Rage Electronics',
    title: 'Electrical and Device Support',
    rating: 4.2,
    reviewCount: 6,
    yearsExperience: 'Electronics service business',
    startingPrice: 19,
    isAvailable: true,
    isVerified: false,
    responseTime: 'Responds in 50 min',
    about: 'Local electronics business adapted here for light electrical help, diagnostics, and setup support.',
    location: 'Djibouti City',
    contactPhone: '+25377881122',
    servicesJson: ['Electrical diagnostics', 'Small installation help', 'Device setup'],
    highlightsJson: ['Electronics background', 'On-site support'],
    bookingModesJson: ['Home Visit', 'Phone Advice'],
    availabilityJson: { weekdays: '09:00 AM - 06:00 PM', saturday: '09:00 AM - 02:00 PM', sunday: 'Closed' },
  },
  {
    id: 'hsp-12',
    categoryId: 'hs-ac',
    name: 'Climatech Djibouti',
    title: 'Cooling and AC Support',
    rating: 4.4,
    reviewCount: 5,
    yearsExperience: 'Cooling maintenance provider',
    startingPrice: 25,
    isAvailable: true,
    isVerified: false,
    responseTime: 'Responds in 45 min',
    about: 'Cooling-service business adapted for AC maintenance, inspection, and repair scheduling inside the app.',
    location: 'Djibouti City',
    contactPhone: '+25377895544',
    servicesJson: ['AC maintenance', 'Cooling inspection', 'Gas refill'],
    highlightsJson: ['Cooling support', 'Maintenance-focused'],
    bookingModesJson: ['Home Visit'],
    availabilityJson: { weekdays: '08:30 AM - 06:00 PM', saturday: '09:00 AM - 01:00 PM', sunday: 'Closed' },
  },
  {
    id: 'hsp-13',
    categoryId: 'hs-electrical',
    name: 'Sos High Tech',
    title: 'Electronics and Technical Support',
    rating: 3.5,
    reviewCount: 7,
    yearsExperience: 'Tech store and support point',
    startingPrice: 18,
    isAvailable: true,
    isVerified: false,
    responseTime: 'Responds in 50 min',
    about: 'Electronics-store identity adapted here for setup help, diagnostics, and in-home tech support.',
    location: 'Rue Pierre Curie, Djibouti City',
    contactPhone: '+25321358080',
    servicesJson: ['Device setup', 'Electrical diagnostics', 'Small repairs'],
    highlightsJson: ['Tech support', 'City-center electronics'],
    bookingModesJson: ['Home Visit', 'Phone Advice'],
    availabilityJson: { weekdays: '09:00 AM - 06:00 PM', saturday: '09:00 AM - 02:00 PM', sunday: 'Closed' },
  },
  {
    id: 'hsp-14',
    categoryId: 'hs-electrical',
    name: 'Arta electronique',
    title: 'Electronics Installer',
    rating: 4.0,
    reviewCount: 7,
    yearsExperience: 'Electronics retailer',
    startingPrice: 21,
    isAvailable: true,
    isVerified: false,
    responseTime: 'Responds in 45 min',
    about: 'Local electronics business adapted for appliance setup and basic home tech support.',
    location: 'Djibouti City',
    contactPhone: '+25321350700',
    servicesJson: ['TV installation', 'Home electronics setup', 'Device checks'],
    highlightsJson: ['Appliance support', 'Electronics store'],
    bookingModesJson: ['Home Visit'],
    availabilityJson: { weekdays: '09:00 AM - 05:30 PM', saturday: '09:00 AM - 01:00 PM', sunday: 'Closed' },
  },
  {
    id: 'hsp-15',
    categoryId: 'hs-beauty',
    name: 'Touch Me Perfumes and Cosmetics',
    title: 'Beauty and Cosmetics',
    rating: 5.0,
    reviewCount: 8,
    yearsExperience: 'Beauty retail and styling',
    startingPrice: 14,
    isAvailable: true,
    isVerified: true,
    responseTime: 'Responds in 30 min',
    about: 'Djibouti beauty listing adapted into the app for makeup support, perfume styling, and event prep.',
    location: "Rue d'Ethiopie, La Plaine, Djibouti City",
    contactPhone: '+25377555562',
    servicesJson: ['Makeup session', 'Cosmetics styling', 'Event beauty prep'],
    highlightsJson: ['Beauty aids listing', 'Highly rated'],
    bookingModesJson: ['Home Visit'],
    availabilityJson: { weekdays: '10:00 AM - 08:00 PM', saturday: '10:00 AM - 07:00 PM', sunday: '11:00 AM - 04:00 PM' },
  },
  {
    id: 'hsp-16',
    categoryId: 'hs-beauty',
    name: 'Boutique Miss Paris',
    title: 'Beauty Boutique',
    rating: 4.5,
    reviewCount: 7,
    yearsExperience: 'Beauty and cosmetics boutique',
    startingPrice: 13,
    isAvailable: true,
    isVerified: false,
    responseTime: 'Responds in 35 min',
    about: 'Local beauty boutique adapted for at-home beauty bookings and cosmetic-focused appointments.',
    location: 'Central Djibouti City',
    contactPhone: '+25321254242',
    servicesJson: ['Beauty consultation', 'Makeup support', 'Fragrance styling'],
    highlightsJson: ['Beauty boutique', 'Local cosmetics'],
    bookingModesJson: ['Home Visit'],
    availabilityJson: { weekdays: '10:00 AM - 07:30 PM', saturday: '10:00 AM - 07:00 PM', sunday: 'Closed' },
  },
  {
    id: 'hsp-17',
    categoryId: 'hs-handyman',
    name: 'Almajd Store Hardware Iphone and Samsung',
    title: 'Hardware and Handyman Support',
    rating: 5.0,
    reviewCount: 5,
    yearsExperience: 'Hardware and device store',
    startingPrice: 16,
    isAvailable: true,
    isVerified: false,
    responseTime: 'Responds in 55 min',
    about: 'Hardware-store identity adapted for practical household fixes, mounting, and minor installation work.',
    location: 'Central Djibouti City',
    contactPhone: '+25377265735',
    servicesJson: ['Minor repairs', 'Hardware installation', 'Wall mounting'],
    highlightsJson: ['Hardware-focused', 'Local utility support'],
    bookingModesJson: ['Home Visit'],
    availabilityJson: { weekdays: '08:30 AM - 05:30 PM', saturday: '09:00 AM - 02:00 PM', sunday: 'Closed' },
  },
  {
    id: 'hsp-18',
    categoryId: 'hs-handyman',
    name: 'Wassel Quincaillerie - AV.13',
    title: 'Avenue 13 Hardware Support',
    rating: 4.1,
    reviewCount: 12,
    yearsExperience: 'Household equipment retailer',
    startingPrice: 17,
    isAvailable: true,
    isVerified: true,
    responseTime: 'Responds in 40 min',
    about: 'Mapped from Avenue 13 retail into practical home support for minor installs, fittings, and hardware needs.',
    location: 'Avenue 13, La Plaine, Djibouti City',
    contactPhone: '+25321345344',
    servicesJson: ['Minor installation', 'Household fittings', 'Utility hardware help'],
    highlightsJson: ['Avenue 13', 'La Plaine', 'Hardware-backed support'],
    bookingModesJson: ['Home Visit'],
    availabilityJson: { weekdays: '08:00 AM - 06:00 PM', saturday: '09:00 AM - 02:00 PM', sunday: 'Closed' },
  },
  {
    id: 'hsp-19',
    categoryId: 'hs-handyman',
    name: 'Ets Abdoulbasset',
    title: 'Neighborhood Utility Support',
    rating: 4.2,
    reviewCount: 10,
    yearsExperience: 'Department-store utility support',
    startingPrice: 16,
    isAvailable: true,
    isVerified: true,
    responseTime: 'Responds in 45 min',
    about: 'Avenue 13 department-store identity adapted for local utility fixes and household support.',
    location: 'Avenue 13, La Plaine, Djibouti City',
    contactPhone: '+25321352888',
    servicesJson: ['Minor home fixes', 'Utility replacements', 'Basic install help'],
    highlightsJson: ['Avenue 13 corridor', 'Neighborhood coverage'],
    bookingModesJson: ['Home Visit'],
    availabilityJson: { weekdays: '08:00 AM - 06:00 PM', saturday: '08:30 AM - 02:00 PM', sunday: 'Closed' },
  },
] as const;
