import { ModuleType } from '@prisma/client';

export const djiboutiHealthServiceCategories = [
  {
    id: 'hsc-lab-tests',
    name: 'Lab Tests at Home',
    slug: 'lab-tests',
    description: 'Convenient lab tests collected from your home.',
    iconKey: 'science',
    colorHex: '#3B82F6',
    sortOrder: 1,
    active: true,
  },
  {
    id: 'hsc-physiotherapy',
    name: 'Physiotherapy',
    slug: 'physiotherapy',
    description: 'Physical therapy and rehabilitation services at home.',
    iconKey: 'accessibility_new',
    colorHex: '#FF9800',
    sortOrder: 2,
    active: true,
  },
  {
    id: 'hsc-consultation',
    name: 'Doctor Consultation',
    slug: 'consultation',
    description: 'Medical consultations with qualified doctors.',
    iconKey: 'medical_services',
    colorHex: '#10B981',
    sortOrder: 3,
    active: true,
  },
] as const;

export const djiboutiLabTests = [
  // Lab Tests
  {
    id: 'lt-1',
    categoryId: 'hsc-lab-tests',
    name: 'Complete Blood Count (CBC)',
    description: 'A complete blood count to check your overall health.',
    fullDescription: 'The complete blood count (CBC) is a blood test used to evaluate your overall health and detect a wide range of disorders, including anemia, infection, and leukemia.',
    price: 1500,
    originalPrice: 1800,
    preparationInstructions: 'Fasting for 8-12 hours may be required.',
    sampleType: 'Blood',
    durationLabel: '15 min',
    active: true,
    sortOrder: 1,
  },
  {
    id: 'lt-2',
    categoryId: 'hsc-lab-tests',
    name: 'Lipid Profile',
    description: 'Measures cholesterol and triglycerides in your blood.',
    fullDescription: 'A lipid profile is a blood test that measures cholesterol and triglycerides in your blood. It helps assess your risk of heart disease.',
    price: 2500,
    originalPrice: null,
    preparationInstructions: 'Fasting for 9-12 hours required.',
    sampleType: 'Blood',
    durationLabel: '20 min',
    active: true,
    sortOrder: 2,
  },
  {
    id: 'lt-3',
    categoryId: 'hsc-lab-tests',
    name: 'Liver Function Test (LFT)',
    description: 'Evaluates liver health and function.',
    fullDescription: 'Liver function tests (LFTs) are blood tests used to assess how well the liver is working and to detect liver damage.',
    price: 2200,
    originalPrice: 2600,
    preparationInstructions: 'Fasting may be required. Avoid alcohol before test.',
    sampleType: 'Blood',
    durationLabel: '15 min',
    active: true,
    sortOrder: 3,
  },
  // Physiotherapy Services
  {
    id: 'pt-1',
    categoryId: 'hsc-physiotherapy',
    name: 'Physical Therapy Evaluation',
    description: 'Initial assessment and treatment plan.',
    fullDescription: 'Comprehensive evaluation of your physical condition, including range of motion, strength, and functional abilities to create a personalized treatment plan.',
    price: 3000,
    originalPrice: null,
    preparationInstructions: 'Wear comfortable clothing and be ready to move.',
    sampleType: null,
    durationLabel: '45 min',
    active: true,
    sortOrder: 1,
  },
  {
    id: 'pt-2',
    categoryId: 'hsc-physiotherapy',
    name: 'Therapeutic Exercise Session',
    description: 'Guided exercises to improve strength and flexibility.',
    fullDescription: 'One-on-one session with a physiotherapist guiding you through exercises tailored to your condition and recovery goals.',
    price: 2500,
    originalPrice: 2800,
    preparationInstructions: 'Wear athletic clothing. Bring any assistive devices you use.',
    sampleType: null,
    durationLabel: '60 min',
    active: true,
    sortOrder: 2,
  },
  {
    id: 'pt-3',
    categoryId: 'hsc-physiotherapy',
    name: 'Manual Therapy',
    description: 'Hands-on techniques to improve mobility and reduce pain.',
    fullDescription: 'Manual therapy involves hands-on techniques to manipulate muscles, joints, and soft tissues to improve mobility, reduce pain, and restore function.',
    price: 3500,
    originalPrice: null,
    preparationInstructions: 'Wear loose, comfortable clothing.',
    sampleType: null,
    durationLabel: '45 min',
    active: true,
    sortOrder: 3,
  },
  // Consultation Services
  {
    id: 'cs-1',
    categoryId: 'hsc-consultation',
    name: 'General Consultation',
    description: 'General medical consultation for common health concerns.',
    fullDescription: 'A comprehensive medical consultation with a qualified doctor to address your health concerns, perform examinations, and provide treatment recommendations.',
    price: 2000,
    originalPrice: 2500,
    preparationInstructions: 'Bring any previous medical records and a list of current medications.',
    sampleType: null,
    durationLabel: '30 min',
    active: true,
    sortOrder: 1,
  },
  {
    id: 'cs-2',
    categoryId: 'hsc-consultation',
    name: 'Specialist Consultation',
    description: 'Consultation with a medical specialist for specific conditions.',
    fullDescription: 'In-depth consultation with a specialist doctor for specific medical conditions, second opinions, or specialized care.',
    price: 4000,
    originalPrice: null,
    preparationInstructions: 'Bring referral documents and relevant test results.',
    sampleType: null,
    durationLabel: '45 min',
    active: true,
    sortOrder: 2,
  },
  {
    id: 'cs-3',
    categoryId: 'hsc-consultation',
    name: 'Follow-up Consultation',
    description: 'Follow-up visit to monitor treatment progress.',
    fullDescription: 'A follow-up consultation to review your progress, adjust treatments, and address any new concerns that have arisen since your last visit.',
    price: 1500,
    originalPrice: null,
    preparationInstructions: 'Bring any recent test results or notes about your condition.',
    sampleType: null,
    durationLabel: '20 min',
    active: true,
    sortOrder: 3,
  },
] as const;
