services:
  - type: web
    name: edalab-backend
    runtime: node
    rootDir: backend
    plan: free
    healthCheckPath: /api/health
    buildCommand: npm install && npm run build
    preDeployCommand: npx prisma db push
    startCommand: npm run start
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: CORS_ORIGIN
        value: "*"
      - key: DATABASE_URL
        sync: false
      - key: DIRECT_URL
        sync: false
      - key: JWT_SECRET
        sync: false
