// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAz5Sd-zPRRZjtDyXLl_sKAfjaAZ2F9txo',
    appId: '1:491118296425:web:3a7c71ce0f53a8e7d611f8',
    messagingSenderId: '491118296425',
    projectId: 'edalab-app',
    authDomain: 'edalab-app.firebaseapp.com',
    databaseURL: 'https://edalab-app-default-rtdb.firebaseio.com',
    storageBucket: 'edalab-app.firebasestorage.app',
    measurementId: 'G-X95L1T6SV5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD43z5Xr1IhSQ-SNgBj95SAzN_C53EiymU',
    appId: '1:491118296425:android:a9a732b9274af060d611f8',
    messagingSenderId: '491118296425',
    projectId: 'edalab-app',
    databaseURL: 'https://edalab-app-default-rtdb.firebaseio.com',
    storageBucket: 'edalab-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsNASUJUiFvCDjhy0xa0bdtpfnoVBlrqE',
    appId: '1:491118296425:ios:5b567db1e2e4a3acd611f8',
    messagingSenderId: '491118296425',
    projectId: 'edalab-app',
    databaseURL: 'https://edalab-app-default-rtdb.firebaseio.com',
    storageBucket: 'edalab-app.firebasestorage.app',
    androidClientId: '491118296425-9ehs3eho2uqfrfr31pm2acoqa35qh7ri.apps.googleusercontent.com',
    iosClientId: '491118296425-2kkehvinu7u3tcfd6iv93p940c5hbi8f.apps.googleusercontent.com',
    iosBundleId: 'com.example.edalabPro',
  );
}
